import { BUSINESS_TIMEZONE, mapRows } from './reporting-common.js';

const HANDOVER_CURRENCY_CTE = `WITH handover_currency AS (
  SELECT line.installation_id,
         line.handover_id,
         count(DISTINCT collection.currency_code)::integer AS currency_count,
         min(collection.currency_code) AS line_currency_code
    FROM accounting.cod_cash_handover_lines line
    JOIN accounting.cod_collections collection
      ON collection.installation_id = line.installation_id
     AND collection.id = line.collection_id
   WHERE line.installation_id = $1
   GROUP BY line.installation_id, line.handover_id
), scoped_handovers AS (
  SELECT handover.*,
         COALESCE(currency.currency_count, 0) AS currency_count,
         CASE WHEN currency.currency_count = 1 THEN currency.line_currency_code ELSE NULL END AS currency_code
    FROM reporting.phase6f_cod_handover_reconciliation handover
    LEFT JOIN handover_currency currency
      ON currency.installation_id = handover.installation_id
     AND currency.handover_id = handover.handover_id
   WHERE handover.installation_id = $1
     AND handover.warehouse_id = ANY($2::uuid[])
     AND ($5::uuid IS NULL OR handover.warehouse_id = $5::uuid)
)`;

export async function codReport(adapter, requestContext, filters, warehouseIds) {
  const params = [requestContext.installationId, warehouseIds, filters.fromInstant, filters.toExclusiveInstant, filters.warehouseId, requestContext.receivedAt];
  const [warehouses, custodyTotals, custodyDrivers, collectionActivity, handoverActivity, acceptanceActivity, pendingHandovers, discrepancies, overduePromises, recentCollections, recentHandovers, lifecycleAnomalies, currencyExceptions] = await Promise.all([
    adapter.query(`SELECT id AS warehouse_id, code AS warehouse_code, name AS warehouse_name FROM shared.warehouses WHERE installation_id = $1 AND id = ANY($2::uuid[]) ORDER BY code, name, id`, [requestContext.installationId, warehouseIds]),
    adapter.query(`SELECT currency_code, count(*)::text AS collection_count, COALESCE(sum(custody_remaining_amount), 0)::text AS custody_remaining_amount FROM reporting.phase6f_cod_collection_reconciliation WHERE installation_id = $1 AND warehouse_id = ANY($2::uuid[]) AND ($5::uuid IS NULL OR warehouse_id = $5::uuid) AND NOT reversed AND collection_method = 'CASH' AND custody_remaining_amount > 0 GROUP BY currency_code ORDER BY currency_code`, params),
    adapter.query(`SELECT driver_profile_id, driver_code, driver_name, currency_code, count(*)::text AS collection_count, COALESCE(sum(custody_remaining_amount), 0)::text AS custody_remaining_amount, min(collected_at) AS oldest_collected_at, GREATEST(0, floor(extract(epoch FROM ($6::timestamptz - min(collected_at))) / 86400))::text AS oldest_age_days FROM reporting.phase6f_cod_collection_reconciliation WHERE installation_id = $1 AND warehouse_id = ANY($2::uuid[]) AND ($5::uuid IS NULL OR warehouse_id = $5::uuid) AND NOT reversed AND collection_method = 'CASH' AND custody_remaining_amount > 0 GROUP BY driver_profile_id, driver_code, driver_name, currency_code ORDER BY sum(custody_remaining_amount) DESC, driver_code, currency_code LIMIT 100`, params),
    adapter.query(`SELECT currency_code, collection_method, collection_status, count(*)::text AS collection_count, COALESCE(sum(expected_amount), 0)::text AS expected_amount, COALESCE(sum(received_amount), 0)::text AS received_amount FROM reporting.phase6f_cod_collection_reconciliation WHERE installation_id = $1 AND warehouse_id = ANY($2::uuid[]) AND ($5::uuid IS NULL OR warehouse_id = $5::uuid) AND collected_at >= $3::timestamptz AND collected_at < $4::timestamptz AND NOT reversed GROUP BY currency_code, collection_method, collection_status ORDER BY currency_code, collection_method, collection_status`, params),
    adapter.query(`${HANDOVER_CURRENCY_CTE} SELECT currency_code, count(*)::text AS handover_count, COALESCE(sum(claimed_amount), 0)::text AS claimed_amount, COALESCE(sum(handover_difference_amount), 0)::text AS handover_difference_amount FROM scoped_handovers WHERE handed_over_at >= $3::timestamptz AND handed_over_at < $4::timestamptz AND projection_status <> 'reversed' AND currency_count = 1 GROUP BY currency_code ORDER BY currency_code`, params),
    adapter.query(`${HANDOVER_CURRENCY_CTE} SELECT currency_code, count(*)::text AS acceptance_count, COALESCE(sum(accepted_amount), 0)::text AS accepted_amount, COALESCE(sum(variance_amount), 0)::text AS variance_amount FROM scoped_handovers WHERE accepted_at >= $3::timestamptz AND accepted_at < $4::timestamptz AND projection_status IN ('reconciled', 'discrepancy') AND currency_count = 1 GROUP BY currency_code ORDER BY currency_code`, params),
    adapter.query(`${HANDOVER_CURRENCY_CTE} SELECT handover_id, warehouse_id, warehouse_code, warehouse_name, trip_id, trip_number, driver_profile_id, driver_code, driver_name, currency_code, claimed_amount::text, pending_acceptance_amount::text, handed_over_at, projection_status FROM scoped_handovers WHERE projection_status IN ('submitted', 'acceptance_reversed') AND currency_count = 1 ORDER BY handed_over_at ASC, handover_id LIMIT 100`, params),
    adapter.query(`${HANDOVER_CURRENCY_CTE} SELECT handover_id, warehouse_id, warehouse_code, warehouse_name, trip_id, trip_number, driver_profile_id, driver_code, driver_name, currency_code, claimed_amount::text, accepted_amount::text, handover_difference_amount::text, variance_amount::text, handed_over_at, accepted_at, projection_status FROM scoped_handovers WHERE projection_status = 'discrepancy' AND currency_count = 1 ORDER BY COALESCE(accepted_at, handed_over_at) ASC, handover_id LIMIT 100`, params),
    adapter.query(`SELECT collection.id AS collection_id, collection.warehouse_id, warehouse.code AS warehouse_code, warehouse.name AS warehouse_name, collection.trip_id, trip.trip_number, collection.delivery_order_id, delivery_order.delivery_order_number, collection.driver_profile_id, driver.code AS driver_code, driver.name AS driver_name, collection.currency_code, collection.expected_amount::text, collection.reason_code, collection.promised_by, collection.due_at, GREATEST(0, floor(extract(epoch FROM ($6::timestamptz - collection.due_at)) / 86400))::text AS overdue_days FROM accounting.cod_collections collection JOIN shared.warehouses warehouse ON warehouse.installation_id = collection.installation_id AND warehouse.id = collection.warehouse_id JOIN logistics.delivery_trips trip ON trip.installation_id = collection.installation_id AND trip.id = collection.trip_id JOIN sales.delivery_orders delivery_order ON delivery_order.installation_id = collection.installation_id AND delivery_order.id = collection.delivery_order_id JOIN logistics.driver_profiles driver ON driver.installation_id = collection.installation_id AND driver.id = collection.driver_profile_id LEFT JOIN accounting.cod_collection_reversals reversal ON reversal.installation_id = collection.installation_id AND reversal.collection_id = collection.id WHERE collection.installation_id = $1 AND collection.warehouse_id = ANY($2::uuid[]) AND ($5::uuid IS NULL OR collection.warehouse_id = $5::uuid) AND reversal.id IS NULL AND collection.collection_method = 'NONE' AND collection.collection_status = 'not_collected' AND collection.due_at < $6::timestamptz ORDER BY collection.due_at ASC, collection.id LIMIT 100`, params),
    adapter.query(`SELECT collection_id, customer_id, customer_code, customer_name, warehouse_id, warehouse_code, trip_id, trip_number, delivery_order_id, delivery_order_number, driver_profile_id, driver_code, driver_name, collection_method, collection_status, currency_code, expected_amount::text, received_amount::text, handed_over_amount::text, custody_remaining_amount::text, collected_at, lifecycle_status, lifecycle_matches FROM reporting.phase6f_cod_collection_reconciliation WHERE installation_id = $1 AND warehouse_id = ANY($2::uuid[]) AND ($5::uuid IS NULL OR warehouse_id = $5::uuid) AND collected_at >= $3::timestamptz AND collected_at < $4::timestamptz ORDER BY collected_at DESC, collection_id LIMIT 100`, params),
    adapter.query(`${HANDOVER_CURRENCY_CTE} SELECT handover_id, warehouse_id, warehouse_code, warehouse_name, trip_id, trip_number, driver_profile_id, driver_code, driver_name, currency_code, currency_count::text, expected_total::text, claimed_amount::text, pending_acceptance_amount::text, accepted_amount::text, handover_difference_amount::text, variance_amount::text, projection_status, handed_over_at, accepted_at, lifecycle_matches FROM scoped_handovers WHERE handed_over_at >= $3::timestamptz AND handed_over_at < $4::timestamptz ORDER BY handed_over_at DESC, handover_id LIMIT 100`, params),
    adapter.query(`SELECT anomaly_type, source_id, source_number, reconciliation_status, details, warehouse_id FROM reporting.phase6f_closeout_anomalies WHERE installation_id = $1 AND warehouse_id = ANY($2::uuid[]) AND ($5::uuid IS NULL OR warehouse_id = $5::uuid) AND anomaly_type IN ('cod_collection', 'cod_handover') ORDER BY anomaly_type, source_number, source_id LIMIT 100`, params),
    adapter.query(`${HANDOVER_CURRENCY_CTE} SELECT handover_id, warehouse_id, warehouse_code, warehouse_name, trip_id, trip_number, driver_profile_id, driver_code, driver_name, currency_count::text, handed_over_at, projection_status FROM scoped_handovers WHERE projection_status <> 'reversed' AND currency_count <> 1 ORDER BY handed_over_at DESC, handover_id LIMIT 100`, params),
  ]);
  return Object.freeze({ generatedAt: requestContext.receivedAt, businessTimezone: BUSINESS_TIMEZONE, filters: Object.freeze({ from: filters.from, to: filters.to, warehouseId: filters.warehouseId }), warehouses: mapRows(warehouses.rows), currentSnapshot: Object.freeze({ custodyByCurrency: mapRows(custodyTotals.rows), custodyByDriver: mapRows(custodyDrivers.rows), overduePromises: mapRows(overduePromises.rows), pendingHandovers: mapRows(pendingHandovers.rows), discrepancies: mapRows(discrepancies.rows) }), activity: Object.freeze({ collections: mapRows(collectionActivity.rows), handovers: mapRows(handoverActivity.rows), acceptances: mapRows(acceptanceActivity.rows), recentCollections: mapRows(recentCollections.rows), recentHandovers: mapRows(recentHandovers.rows) }), exceptions: Object.freeze({ lifecycle: mapRows(lifecycleAnomalies.rows), currencyLineage: mapRows(currencyExceptions.rows) }) });
}
