import 'server-only';

import { createIdempotencyKey, isValidIdempotencyKey, normalizeIdempotencyKey } from '@npp/contracts';
import { randomUUID } from 'node:crypto';
import { requireNppWorkforceSessionToken } from './internal-auth-client';

const REQUEST_ID_PATTERN = /^[A-Za-z0-9._:-]{1,128}$/;
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const REQUEST_TIMEOUT_MS = 8_000;
const EMPLOYEE_PAGE_SIZE = 1000;
const MAX_EMPLOYEE_OFFSET = 10_000_000;
const ALLOWED_QUERY_KEYS = new Set(['active', 'limit', 'offset', 'branchId']);
interface CoreEnvelope<T>{data?:T;error?:{code?:string;message?:string;retryable?:boolean;details?:unknown};requestId?:string}
export class EmployeeGatewayError extends Error{constructor(public readonly code:string,public readonly publicMessage:string,public readonly statusCode:number,public readonly retryable:boolean,public readonly details:unknown={}){super(publicMessage);this.name='EmployeeGatewayError';}}
export function resolveEmployeeRequestId(value:string|null|undefined){const c=String(value??'').trim();return REQUEST_ID_PATTERN.test(c)?c:`web_${randomUUID()}`;}
export function normalizeEmployeeGatewayError(error:unknown){return error instanceof EmployeeGatewayError?error:new EmployeeGatewayError('EMPLOYEE_GATEWAY_UNAVAILABLE','Dữ liệu nhân sự tạm thời chưa sẵn sàng',503,true);}
function requiredServerValue(name:'CORE_API_INTERNAL_URL'|'CORE_API_SERVER_TOKEN'){if(name==='CORE_API_SERVER_TOKEN')return requireNppWorkforceSessionToken();const v=process.env[name]?.trim();if(!v)throw new EmployeeGatewayError('EMPLOYEE_GATEWAY_NOT_CONFIGURED','Cổng dữ liệu nhân sự chưa được cấu hình',503,false);return v;}
function coreApiBaseUrl(){let u:URL;try{u=new URL(requiredServerValue('CORE_API_INTERNAL_URL'));}catch{throw new EmployeeGatewayError('EMPLOYEE_GATEWAY_NOT_CONFIGURED','Cổng dữ liệu nhân sự chưa được cấu hình',503,false);}if(!['http:','https:'].includes(u.protocol)||u.username||u.password||(process.env.NODE_ENV==='production'&&u.protocol!=='https:'))throw new EmployeeGatewayError('EMPLOYEE_GATEWAY_NOT_CONFIGURED','Cổng dữ liệu nhân sự chưa được cấu hình',503,false);u.pathname=u.pathname.replace(/\/$/,'');u.search='';u.hash='';return u.toString().replace(/\/$/,'');}
function safeQuery(p:URLSearchParams){const n=new URLSearchParams();for(const[k,v]of p.entries())if(ALLOWED_QUERY_KEYS.has(k)&&v.length<=128)n.append(k,v);const s=n.toString();return s?`?${s}`:'';}
function mutationKey(value:string|undefined){const n=normalizeIdempotencyKey(value);if(!n)return createIdempotencyKey('web-employee-create');if(!isValidIdempotencyKey(n))throw new EmployeeGatewayError('INVALID_IDEMPOTENCY_KEY','Khóa chống trùng yêu cầu không hợp lệ',400,false);return n;}
async function requestCore<T>({id,method,requestId,searchParams,body,idempotencyKey}:{id?:string;method:'GET'|'POST'|'PATCH';requestId:string;searchParams?:URLSearchParams;body?:unknown;idempotencyKey?:string}){if(id&&!UUID_PATTERN.test(id))throw new EmployeeGatewayError('INVALID_EMPLOYEE_ID','Mã định danh nhân sự không hợp lệ',400,false);const c=new AbortController();const t=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{const path=`/api/employees${id?`/${id}`:''}${searchParams?safeQuery(searchParams):''}`;const r=await fetch(`${coreApiBaseUrl()}${path}`,{method,cache:'no-store',signal:c.signal,headers:{Authorization:`Bearer ${requiredServerValue('CORE_API_SERVER_TOKEN')}`,Accept:'application/json','x-request-id':requestId,...(body===undefined?{}:{'Content-Type':'application/json'}),...(idempotencyKey?{'Idempotency-Key':idempotencyKey}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});let p:CoreEnvelope<T>;try{p=await r.json() as CoreEnvelope<T>;}catch{throw new EmployeeGatewayError('EMPLOYEE_GATEWAY_RESPONSE_INVALID','Core API trả về phản hồi không hợp lệ',502,false);}if(!r.ok)throw new EmployeeGatewayError(p.error?.code||'EMPLOYEE_REQUEST_FAILED',p.error?.message||'Yêu cầu dữ liệu nhân sự thất bại',r.status,p.error?.retryable===true,p.error?.details??{});if(!Object.prototype.hasOwnProperty.call(p,'data'))throw new EmployeeGatewayError('EMPLOYEE_GATEWAY_RESPONSE_INVALID','Core API trả về phản hồi không hợp lệ',502,false);return p.data as T;}catch(e){if(e instanceof EmployeeGatewayError)throw e;throw new EmployeeGatewayError('EMPLOYEE_GATEWAY_UNAVAILABLE','Core API tạm thời không khả dụng',503,true);}finally{clearTimeout(t);}}
export function listEmployees<T>(requestId:string,searchParams:URLSearchParams):Promise<T>{return requestCore<T>({method:'GET',requestId,searchParams});}
export async function listAllEmployees<T>(requestId:string,searchParams=new URLSearchParams()):Promise<T[]>{const filters=new URLSearchParams(searchParams);filters.delete('limit');filters.delete('offset');const employees:T[]=[];let offset=0;while(true){const pageParams=new URLSearchParams(filters);pageParams.set('limit',String(EMPLOYEE_PAGE_SIZE));pageParams.set('offset',String(offset));const page=await requestCore<T[]>({method:'GET',requestId,searchParams:pageParams});employees.push(...page);if(page.length<EMPLOYEE_PAGE_SIZE)return employees;offset+=page.length;if(offset>MAX_EMPLOYEE_OFFSET)throw new EmployeeGatewayError('EMPLOYEE_DIRECTORY_TOO_LARGE','Danh mục nhân sự vượt quá giới hạn đồng bộ hiện tại',422,false);}}
export function getEmployee<T>(id:string,requestId:string):Promise<T>{return requestCore<T>({id,method:'GET',requestId});}
export function createEmployee<T>(requestId:string,body:unknown,idempotencyKey?:string):Promise<T>{return requestCore<T>({method:'POST',requestId,body,idempotencyKey:mutationKey(idempotencyKey)});}
export function patchEmployee<T>(id:string,requestId:string,body:unknown):Promise<T>{return requestCore<T>({id,method:'PATCH',requestId,body});}
