import 'server-only';
import { randomUUID } from 'node:crypto';
import { requireNppWorkforceSessionToken } from './internal-auth-client';
export const ORGANIZATION_RESOURCES=['branches','warehouses','warehouse-locations'] as const;export type OrganizationResource=(typeof ORGANIZATION_RESOURCES)[number];
const RESOURCE_SET=new Set<string>(ORGANIZATION_RESOURCES);const REQUEST_ID_PATTERN=/^[A-Za-z0-9._:-]{1,128}$/;const UUID_PATTERN=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const REQUEST_TIMEOUT_MS=8_000;const ALLOWED_QUERY_KEYS=new Set(['active','limit','offset','branchId','warehouseId']);
interface CoreEnvelope<T>{data?:T;error?:{code?:string;message?:string;retryable?:boolean;details?:unknown};requestId?:string;receivedAt?:string}
export class OrganizationGatewayError extends Error{constructor(public readonly code:string,public readonly publicMessage:string,public readonly statusCode:number,public readonly retryable:boolean,public readonly details:unknown={}){super(publicMessage);this.name='OrganizationGatewayError';}}
export function isOrganizationResource(value:string):value is OrganizationResource{return RESOURCE_SET.has(value);}export function resolveOrganizationRequestId(value:string|null|undefined){const c=String(value??'').trim();return REQUEST_ID_PATTERN.test(c)?c:`web_${randomUUID()}`;}export function normalizeOrganizationGatewayError(error:unknown){return error instanceof OrganizationGatewayError?error:new OrganizationGatewayError('ORGANIZATION_GATEWAY_UNAVAILABLE','Organization data is temporarily unavailable',503,true);}
function requiredServerValue(name:'CORE_API_INTERNAL_URL'|'CORE_API_SERVER_TOKEN'){if(name==='CORE_API_SERVER_TOKEN')return requireNppWorkforceSessionToken();const v=process.env[name]?.trim();if(!v)throw new OrganizationGatewayError('ORGANIZATION_GATEWAY_NOT_CONFIGURED','Organization gateway is not configured',503,false);return v;}function coreApiBaseUrl(){let u:URL;try{u=new URL(requiredServerValue('CORE_API_INTERNAL_URL'));}catch{throw new OrganizationGatewayError('ORGANIZATION_GATEWAY_NOT_CONFIGURED','Organization gateway is not configured',503,false);}if(!['http:','https:'].includes(u.protocol)||u.username||u.password||(process.env.NODE_ENV==='production'&&u.protocol!=='https:'))throw new OrganizationGatewayError('ORGANIZATION_GATEWAY_NOT_CONFIGURED','Organization gateway is not configured',503,false);u.pathname=u.pathname.replace(/\/$/,'');u.search='';u.hash='';return u.toString().replace(/\/$/,'');}function safeQuery(p:URLSearchParams){const n=new URLSearchParams();for(const[k,v]of p.entries())if(ALLOWED_QUERY_KEYS.has(k)&&v.length<=128)n.append(k,v);const s=n.toString();return s?`?${s}`:'';}function organizationPath(resource:OrganizationResource,id?:string){if(id!==undefined&&!UUID_PATTERN.test(id))throw new OrganizationGatewayError('INVALID_RESOURCE_ID','Resource ID is invalid',400,false);return `/api/${resource}${id?`/${id}`:''}`;}
async function requestCore<T>({resource,id,method,requestId,searchParams,body,idempotencyKey}:{resource:OrganizationResource;id?:string;method:'GET'|'POST'|'PATCH';requestId:string;searchParams?:URLSearchParams;body?:unknown;idempotencyKey?:string}){const c=new AbortController();const t=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{const path=`${organizationPath(resource,id)}${searchParams?safeQuery(searchParams):''}`;const r=await fetch(`${coreApiBaseUrl()}${path}`,{method,cache:'no-store',signal:c.signal,headers:{Authorization:`Bearer ${requiredServerValue('CORE_API_SERVER_TOKEN')}`,Accept:'application/json','x-request-id':requestId,...(body===undefined?{}:{'Content-Type':'application/json'}),...(idempotencyKey?{'Idempotency-Key':idempotencyKey}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});let p:CoreEnvelope<T>;try{p=await r.json() as CoreEnvelope<T>;}catch{throw new OrganizationGatewayError('ORGANIZATION_GATEWAY_RESPONSE_INVALID','Core API returned an invalid response',502,false);}if(!r.ok)throw new OrganizationGatewayError(p.error?.code||'ORGANIZATION_REQUEST_FAILED',p.error?.message||'Organization request failed',r.status,p.error?.retryable===true,p.error?.details??{});if(!Object.prototype.hasOwnProperty.call(p,'data'))throw new OrganizationGatewayError('ORGANIZATION_GATEWAY_RESPONSE_INVALID','Core API returned an invalid response',502,false);return p.data as T;}catch(e){if(e instanceof OrganizationGatewayError)throw e;throw new OrganizationGatewayError('ORGANIZATION_GATEWAY_UNAVAILABLE','Core API is temporarily unavailable',503,true);}finally{clearTimeout(t);}}
export function listOrganizationResource<T>(resource:OrganizationResource,requestId:string,searchParams:URLSearchParams):Promise<T>{return requestCore<T>({resource,method:'GET',requestId,searchParams});}export function getOrganizationResource<T>(resource:OrganizationResource,id:string,requestId:string):Promise<T>{return requestCore<T>({resource,id,method:'GET',requestId});}export function createOrganizationResource<T>(resource:OrganizationResource,requestId:string,body:unknown,idempotencyKey?:string):Promise<T>{return requestCore<T>({resource,method:'POST',requestId,body,idempotencyKey:idempotencyKey?.trim()||`web-${randomUUID()}`});}export function patchOrganizationResource<T>(resource:OrganizationResource,id:string,requestId:string,body:unknown):Promise<T>{return requestCore<T>({resource,id,method:'PATCH',requestId,body});}
