export type SalesOrderStatus = 'draft' | 'confirmed' | 'cancelled' | 'closed';
export type SalesOrderVersionStatus = 'draft' | 'confirmed' | 'superseded' | 'cancelled';
export type SalesOrderCollectionPolicy = 'PREPAID' | 'COLLECT_ON_DELIVERY' | 'COLLECT_AFTER_DELIVERY' | 'CREDIT_TERMS';
export type SalesOrderDeliveryMode = 'DELIVERY' | 'PICKUP';
export type SalesOrderSourceType = 'MANUAL' | 'IMPORT' | 'API' | 'MCP';

export type SalesOrderLine = {
  id: string;
  lineNumber: number;
  variantId: string;
  sku: string;
  itemName: string;
  unitId: string;
  unitCode: string;
  conversionToBase: string;
  quantity: string;
  baseQuantity: string;
  priceListId: string | null;
  priceRuleId: string | null;
  priceSource: 'PRICE_ENGINE' | 'MANUAL_OVERRIDE';
  unitPrice: string;
  discountMode: 'TOTAL_AMOUNT' | 'PER_UNIT' | 'PERCENT';
  discountValue: string;
  discountAmount: string;
  taxMode: 'EXCLUSIVE' | 'INCLUSIVE';
  taxRate: string;
  taxAmount: string;
  lineSubtotal: string;
  lineTotal: string;
  note: string | null;
};

export type SalesOrderVersion = {
  id: string;
  versionNumber: string;
  status: SalesOrderVersionStatus;
  customerId: string;
  customerCode: string;
  customerName: string;
  customerAddressId: string | null;
  customerAddress: Record<string, unknown> | null;
  warehouseId: string;
  warehouseCode: string;
  warehouseName: string;
  deliveryMode: SalesOrderDeliveryMode;
  sourceType: SalesOrderSourceType;
  sourceId: string | null;
  sourceOutletId: string | null;
  collectionPolicy: SalesOrderCollectionPolicy;
  currency: 'VND';
  requestedDeliveryDate: string | null;
  note: string | null;
  subtotal: string;
  discountTotal: string;
  taxTotal: string;
  total: string;
  amendmentReason: string | null;
  basedOnVersionNumber: string | null;
  priceOverrideReason: string | null;
  revision: string;
  createdAt: string;
  createdBy: string;
  confirmedAt: string | null;
  confirmedBy: string | null;
  lines?: SalesOrderLine[];
};

export type SalesOrder = {
  id: string;
  number: string | null;
  status: SalesOrderStatus;
  currentVersionNumber: string;
  sourceType: SalesOrderSourceType;
  sourceId: string | null;
  sourceOutletId: string | null;
  customerId: string;
  customerCode: string;
  customerName: string;
  customerAddressId: string | null;
  warehouseId: string;
  warehouseCode: string;
  warehouseName: string;
  deliveryMode: SalesOrderDeliveryMode;
  collectionPolicy: SalesOrderCollectionPolicy;
  fulfillmentStatus: string;
  deliveryStatus: string;
  settlementStatus: string;
  currency: 'VND';
  requestedDeliveryDate: string | null;
  note: string | null;
  revision: string;
  confirmedAt: string | null;
  confirmedBy: string | null;
  cancelledAt: string | null;
  cancelledBy: string | null;
  cancellationReason: string | null;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
  versions?: SalesOrderVersion[];
};

export type ListSalesOrdersParams = {
  limit?: number;
  offset?: number;
  status?: SalesOrderStatus | 'all';
  customerId?: string;
  warehouseId?: string;
  search?: string;
};

export type SalesOrderLineDraft = {
  variantId: string;
  quantity: string;
  discountMode?: 'TOTAL_AMOUNT' | 'PER_UNIT' | 'PERCENT';
  discountValue?: string;
  taxMode?: 'EXCLUSIVE' | 'INCLUSIVE';
  taxRate?: string;
  manualUnitPriceMinor?: string;
  manualReason?: string;
  note?: string;
};

export type SalesOrderDraftPayload = {
  sourceType?: SalesOrderSourceType;
  sourceId?: string;
  sourceOutletId?: string;
  customerId: string;
  customerAddressId?: string;
  warehouseId: string;
  deliveryMode: SalesOrderDeliveryMode;
  collectionPolicy: SalesOrderCollectionPolicy;
  currency: 'VND';
  requestedDeliveryDate?: string;
  note?: string;
  expectedRevision?: string;
  creditOverrideReason?: string;
  lines: SalesOrderLineDraft[];
};
