export type ReportDomain='executive'|'sales-profit'|'debt'|'inventory'|'delivery-cod'|'mcp'|'people'|'decisions';
export type ReportPreview={id:string;domain:ReportDomain;title:string;source:'Core'|'MCP'|'Core + MCP';period:string;current:string;previous:string;delta:string;trend:'up'|'down'|'flat';summary:string;metrics:{label:string;value:string;note:string}[];highlights:string[]};

export const reportDomainLabel:Record<ReportDomain,string>={executive:'Điều hành','sales-profit':'Kinh doanh & lợi nhuận',debt:'Công nợ',inventory:'Kho','delivery-cod':'Giao vận & COD',mcp:'MCP / thị trường',people:'Nhân sự / hiệu suất',decisions:'Phê duyệt & cảnh báo'};

export const reportPreviews:ReportPreview[]=[
{id:'executive-overview',domain:'executive',title:'Tổng hợp điều hành',source:'Core + MCP',period:'Tháng này',current:'82%',previous:'78%',delta:'+4 điểm',trend:'up',summary:'Ảnh chụp điều hành hợp nhất, ưu tiên các chỉ số cần quản lý theo dõi trên mobile.',metrics:[{label:'Doanh thu',value:'4,82 tỷ',note:'+6,4% so với kỳ trước'},{label:'Lãi gộp',value:'18,7%',note:'+1,2 điểm'},{label:'Công nợ quá hạn',value:'386 triệu',note:'-8,1%'},{label:'Cảnh báo mở',value:'7',note:'2 mức cao'}],highlights:['Doanh thu và lãi gộp cùng cải thiện.','Công nợ quá hạn giảm nhưng còn tập trung ở 3 khách hàng.','Có 2 cảnh báo mức cao cần rà soát trong ngày.']},
{id:'sales-profit',domain:'sales-profit',title:'Kinh doanh & lợi nhuận',source:'Core',period:'Tháng này',current:'18,7%',previous:'17,5%',delta:'+1,2 điểm',trend:'up',summary:'Theo dõi doanh thu, biên lợi nhuận và nhóm sản phẩm/khách hàng tạo biến động chính.',metrics:[{label:'Doanh thu',value:'4,82 tỷ',note:'+6,4%'},{label:'Lãi gộp',value:'902 triệu',note:'+13,8%'},{label:'Biên gộp',value:'18,7%',note:'+1,2 điểm'},{label:'Đơn hàng',value:'286',note:'+4,0%'}],highlights:['Nhóm nguyên liệu A đóng góp tăng trưởng chính.','2 khách hàng có biên gộp thấp hơn mức trung bình.']},
{id:'debt',domain:'debt',title:'Công nợ phải thu',source:'Core',period:'Tháng này',current:'386 triệu',previous:'420 triệu',delta:'-8,1%',trend:'up',summary:'Tập trung vào dư nợ quá hạn, tuổi nợ và khách hàng cần quản lý theo dõi.',metrics:[{label:'Phải thu',value:'1,76 tỷ',note:'Tổng dư nợ'},{label:'Quá hạn',value:'386 triệu',note:'21,9% phải thu'},{label:'>30 ngày',value:'142 triệu',note:'8,1% phải thu'},{label:'Khách cần chú ý',value:'3',note:'Theo ngưỡng quản trị'}],highlights:['Dư nợ quá hạn giảm so với kỳ trước.','Một khách hàng chiếm hơn 35% nợ trên 30 ngày.']},
{id:'inventory',domain:'inventory',title:'Sức khỏe tồn kho',source:'Core',period:'Tháng này',current:'12,4 ngày',previous:'13,1 ngày',delta:'-0,7 ngày',trend:'up',summary:'Theo dõi vòng quay, hàng chậm và các SKU có nguy cơ thiếu hoặc tồn cao.',metrics:[{label:'Ngày tồn bình quân',value:'12,4',note:'-0,7 ngày'},{label:'SKU thấp ngưỡng',value:'8',note:'Cần theo dõi'},{label:'SKU tồn chậm',value:'11',note:'>45 ngày'},{label:'Giá trị tồn',value:'2,14 tỷ',note:'+2,2%'}],highlights:['Vòng quay tồn kho cải thiện nhẹ.','8 SKU đang thấp hơn ngưỡng mục tiêu.']},
{id:'delivery-cod',domain:'delivery-cod',title:'Giao vận & COD',source:'Core',period:'7 ngày',current:'94,6%',previous:'92,9%',delta:'+1,7 điểm',trend:'up',summary:'Theo dõi tỷ lệ giao thành công, chuyến bất thường và COD chưa hoàn tất.',metrics:[{label:'Giao thành công',value:'94,6%',note:'+1,7 điểm'},{label:'Giao thất bại',value:'12',note:'-3 đơn'},{label:'COD chờ bàn giao',value:'74 triệu',note:'4 chuyến'},{label:'Chuyến hoàn tất',value:'39',note:'+5,4%'}],highlights:['Tỷ lệ giao thành công cải thiện.','4 chuyến còn COD chờ bàn giao.']},
{id:'mcp-market',domain:'mcp',title:'MCP / thị trường',source:'MCP',period:'7 ngày',current:'76%',previous:'72%',delta:'+4 điểm',trend:'up',summary:'Tổng hợp độ phủ tuyến, hoạt động thị trường và tín hiệu từ đội ngũ MCP.',metrics:[{label:'Hoàn thành tuyến',value:'76%',note:'+4 điểm'},{label:'Điểm ghé',value:'148',note:'+9,6%'},{label:'Báo cáo thị trường',value:'24',note:'+5 báo cáo'},{label:'Đề xuất gửi Admin',value:'6',note:'2 đang chờ'}],highlights:['Độ phủ tuyến tăng so với kỳ trước.','Khu vực phía Tây có tần suất ghé thấp nhất.']},
{id:'people-performance',domain:'people',title:'Nhân sự / hiệu suất',source:'Core + MCP',period:'Tháng này',current:'88%',previous:'85%',delta:'+3 điểm',trend:'up',summary:'Tổng hợp mức hoàn thành công việc theo vai trò vận hành và thị trường.',metrics:[{label:'Hoàn thành mục tiêu',value:'88%',note:'+3 điểm'},{label:'Nhân sự hoạt động',value:'34',note:'Ổn định'},{label:'Cần hỗ trợ',value:'4',note:'Theo tín hiệu quản trị'},{label:'MCP đạt tuyến',value:'9/12',note:'75%'}],highlights:['Hiệu suất tổng thể tăng nhẹ.','3 MCP chưa đạt ngưỡng hoàn thành tuyến.']},
{id:'decisions',domain:'decisions',title:'Phê duyệt & cảnh báo',source:'Core + MCP',period:'Tháng này',current:'91%',previous:'87%',delta:'+4 điểm',trend:'up',summary:'Theo dõi tốc độ ra quyết định và khối lượng ngoại lệ/cảnh báo quản trị.',metrics:[{label:'Đã xử lý',value:'41',note:'91% trong SLA mẫu'},{label:'Đang chờ duyệt',value:'5',note:'2 ưu tiên cao'},{label:'Cảnh báo mở',value:'7',note:'2 mức cao'},{label:'Chờ bổ sung',value:'2',note:'Cần phản hồi'}],highlights:['Tỷ lệ xử lý trong SLA mẫu tăng.','Hai đề xuất ưu tiên cao đang chờ quyết định.']}
];
