'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import type { CodReportingDashboard } from '../../lib/cod-reporting-types';
import { AppShell } from './app-shell';
import styles from './inventory-reporting-workspace.module.css';

type ApiEnvelope<T> = Readonly<{ data?: T; error?: { message?: string } }>;

function count(value: string | null | undefined) {
  const normalized = String(value ?? '0').trim();
  return /^-?\d+$/.test(normalized) ? normalized.replace(/\B(?=(\d{3})+(?!\d))/g, '.') : normalized;
}
function money(value: string | null | undefined, currency: string | null | undefined) {
  const raw = String(value ?? '0').trim(); const sign = raw.startsWith('-') ? '-' : ''; const unsigned = sign ? raw.slice(1) : raw; const [whole = '0', fraction = ''] = unsigned.split('.'); const grouped = whole.replace(/\B(?=(\d{3})+(?!\d))/g, '.'); const decimal = fraction.replace(/0+$/, ''); return `${sign}${grouped}${decimal ? `,${decimal}` : ''}${currency ? ` ${currency}` : ''}`;
}
function timestamp(value: string | null | undefined) { if (!value) return '—'; try { return new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value)); } catch { return value; } }
function custodyAmountList(rows: readonly { currencyCode: string; custodyRemainingAmount: string }[]) { return rows.length ? rows.map((row) => money(row.custodyRemainingAmount, row.currencyCode)).join(' · ') : '0'; }

export default function CodReportingWorkspace() {
  const [report, setReport] = useState<CodReportingDashboard | null>(null); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [warehouseId, setWarehouseId] = useState(''); const [busy, setBusy] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async (next = { from, to, warehouseId }) => {
    setBusy(true); setError('');
    try {
      const params = new URLSearchParams(); if (next.from) params.set('from', next.from); if (next.to) params.set('to', next.to); if (next.warehouseId) params.set('warehouseId', next.warehouseId); const serialized = params.toString();
      const response = await fetch(`/api/reporting/cod${serialized ? `?${serialized}` : ''}`, { cache: 'no-store' }); const payload = await response.json() as ApiEnvelope<CodReportingDashboard>;
      if (!response.ok || !payload.data) throw new Error(payload.error?.message || 'Không tải được báo cáo COD');
      setReport(payload.data); setFrom(payload.data.filters.from); setTo(payload.data.filters.to); setWarehouseId(payload.data.filters.warehouseId ?? '');
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không tải được báo cáo COD'); } finally { setBusy(false); }
  }, [from, to, warehouseId]);
  useEffect(() => { void load({ from: '', to: '', warehouseId: '' }); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  function submit(event: FormEvent) { event.preventDefault(); void load(); }
  const custodyCount = useMemo(() => report?.currentSnapshot.custodyByCurrency.reduce((sum, row) => sum + BigInt(row.collectionCount), 0n).toString() ?? '0', [report]);
  const pendingCount = String(report?.currentSnapshot.pendingHandovers.length ?? 0);
  const exceptionCount = String((report?.currentSnapshot.discrepancies.length ?? 0) + (report?.exceptions.lifecycle.length ?? 0) + (report?.exceptions.currencyLineage.length ?? 0));

  return <AppShell title="COD & đối soát vận hành" subtitle="Theo dõi tiền khách đã trả, tiền tài xế đang giữ, bàn giao và kế toán tiếp nhận từ cùng nguồn COD canonical."><div className={styles.workspace} data-testid="cod-reporting-workspace">
    <div className={styles.headerActions}><Link className={styles.linkButton} href="/accounting/cod-reconciliation">Mở màn xử lý COD</Link><Link className={styles.linkButton} href="/accounting/reconciliation">Đối soát tổng hợp</Link></div>
    <form className={styles.filters} onSubmit={submit}><label className={styles.field}>Từ ngày<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} disabled={busy} /></label><label className={styles.field}>Đến ngày<input type="date" value={to} onChange={(event) => setTo(event.target.value)} disabled={busy} /></label><label className={styles.field}>Kho<select value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)} disabled={busy}><option value="">Tất cả kho được cấp quyền</option>{report?.warehouses.map((row) => <option key={row.warehouseId} value={row.warehouseId}>{row.warehouseCode} · {row.warehouseName}</option>)}</select></label><button className={styles.primaryButton} type="submit" disabled={busy}>{busy ? 'Đang tải…' : 'Lọc báo cáo'}</button></form>
    <p className={styles.notice}>Khoản tiền mặt tài xế đang giữ là <strong>snapshot hiện tại</strong> và không bị che bởi kỳ báo cáo. Từ/đến ngày chỉ áp dụng cho hoạt động thu, bàn giao và kế toán tiếp nhận.</p>{error ? <p className={styles.error}>{error}</p> : null}
    <section className={styles.cards} aria-label="Tổng quan COD"><article className={styles.card}><span className={styles.cardLabel}>Khoản tiền mặt đang ở tài xế</span><strong className={styles.cardValue}>{count(custodyCount)}</strong><small className={styles.cardHint}>{custodyAmountList(report?.currentSnapshot.custodyByCurrency ?? [])}</small></article><article className={styles.card}><span className={styles.cardLabel}>Bàn giao chờ kế toán nhận</span><strong className={styles.cardValue}>{count(pendingCount)}</strong><small className={styles.cardHint}>Current queue, không bị che bởi kỳ báo cáo</small></article><article className={styles.card}><span className={styles.cardLabel}>Lời hẹn thu đã quá hạn</span><strong className={styles.cardValue}>{count(String(report?.currentSnapshot.overduePromises.length ?? 0))}</strong><small className={styles.cardHint}>Chưa thu tiền, due_at đã qua</small></article><article className={styles.card}><span className={styles.cardLabel}>Ngoại lệ / chênh lệch</span><strong className={styles.cardValue}>{count(exceptionCount)}</strong><small className={styles.cardHint}>Không tự sửa hoặc gộp số liệu</small></article></section>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Tiền mặt đang ở tài xế</h2><p>Customer settlement và driver cash custody là hai trục riêng.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Tài xế</th><th>Currency</th><th className={styles.numeric}>Số collection</th><th className={styles.numeric}>Đang giữ</th><th>Cũ nhất</th></tr></thead><tbody>{report?.currentSnapshot.custodyByDriver.map((row) => <tr key={`${row.driverProfileId}-${row.currencyCode}`}><td>{row.driverCode} · {row.driverName}</td><td>{row.currencyCode}</td><td className={styles.numeric}>{count(row.collectionCount)}</td><td className={styles.numeric}>{money(row.custodyRemainingAmount, row.currencyCode)}</td><td>{timestamp(row.oldestCollectedAt)} · {count(row.oldestAgeDays)} ngày</td></tr>)}{report?.currentSnapshot.custodyByDriver.length === 0 && !busy ? <tr><td colSpan={5} className={styles.empty}>Không có tiền mặt COD đang nằm ở tài xế.</td></tr> : null}</tbody></table></div></section>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Hoạt động thu trong kỳ</h2><p>Tách theo currency, phương thức và trạng thái; không cộng chéo currency.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Currency</th><th>Phương thức</th><th>Trạng thái</th><th className={styles.numeric}>Số lượt</th><th className={styles.numeric}>Phải thu</th><th className={styles.numeric}>Đã nhận</th></tr></thead><tbody>{report?.activity.collections.map((row) => <tr key={`${row.currencyCode}-${row.collectionMethod}-${row.collectionStatus}`}><td>{row.currencyCode}</td><td>{row.collectionMethod}</td><td>{row.collectionStatus}</td><td className={styles.numeric}>{count(row.collectionCount)}</td><td className={styles.numeric}>{money(row.expectedAmount, row.currencyCode)}</td><td className={styles.numeric}>{money(row.receivedAmount, row.currencyCode)}</td></tr>)}</tbody></table></div></section>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Bàn giao chờ kế toán tiếp nhận</h2><p>Đây là tiền đã rời custody tài xế nhưng chưa có acceptance hiện hành.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Chuyến / tài xế</th><th>Kho</th><th>Currency</th><th className={styles.numeric}>Chờ nhận</th><th>Bàn giao lúc</th></tr></thead><tbody>{report?.currentSnapshot.pendingHandovers.map((row) => <tr key={row.handoverId}><td><Link href="/accounting/cod-reconciliation">{row.tripNumber} · {row.driverCode}</Link></td><td>{row.warehouseCode}</td><td>{row.currencyCode ?? '—'}</td><td className={styles.numeric}>{money(row.pendingAcceptanceAmount, row.currencyCode)}</td><td>{timestamp(row.handedOverAt)}</td></tr>)}{report?.currentSnapshot.pendingHandovers.length === 0 && !busy ? <tr><td colSpan={5} className={styles.empty}>Không có bàn giao đang chờ tiếp nhận.</td></tr> : null}</tbody></table></div></section>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Lời hẹn thu đã quá hạn</h2><p>Không biến khoản chưa thu thành tiền tài xế đang giữ.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Phiếu giao</th><th>Chuyến / tài xế</th><th className={styles.numeric}>Số phải thu</th><th>Hẹn bởi</th><th>Quá hạn</th></tr></thead><tbody>{report?.currentSnapshot.overduePromises.map((row) => <tr key={row.collectionId}><td>{row.deliveryOrderNumber ?? row.deliveryOrderId}</td><td>{row.tripNumber} · {row.driverCode}</td><td className={styles.numeric}>{money(row.expectedAmount, row.currencyCode)}</td><td>{row.promisedBy}</td><td>{count(row.overdueDays)} ngày</td></tr>)}{report?.currentSnapshot.overduePromises.length === 0 && !busy ? <tr><td colSpan={5} className={styles.empty}>Không có lời hẹn thu quá hạn.</td></tr> : null}</tbody></table></div></section>
    <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Chênh lệch & ngoại lệ cần xử lý</h2><p>Lifecycle mismatch và handover không xác định được đúng một currency đều được surfaced, không đoán.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Loại</th><th>Nguồn</th><th>Kho</th><th>Chi tiết</th></tr></thead><tbody>{report?.currentSnapshot.discrepancies.map((row) => <tr key={`discrepancy-${row.handoverId}`}><td>Handover discrepancy</td><td><Link href="/accounting/cod-reconciliation">{row.tripNumber} · {row.driverCode}</Link></td><td>{row.warehouseCode}</td><td>{money(row.varianceAmount, row.currencyCode)} · {row.projectionStatus}</td></tr>)}{report?.exceptions.lifecycle.map((row) => <tr key={`lifecycle-${row.anomalyType}-${row.sourceId}`}><td>{row.anomalyType}</td><td><Link href="/accounting/reconciliation">{row.sourceNumber}</Link></td><td>{row.warehouseId}</td><td>{row.reconciliationStatus}</td></tr>)}{report?.exceptions.currencyLineage.map((row) => <tr key={`currency-${row.handoverId}`}><td>Currency lineage</td><td><Link href="/accounting/cod-reconciliation">{row.tripNumber} · {row.driverCode}</Link></td><td>{row.warehouseCode}</td><td>{row.currencyCount} currency trên handover — không đưa vào tổng tiền</td></tr>)}{exceptionCount === '0' && !busy ? <tr><td colSpan={4} className={styles.empty}>Không có ngoại lệ COD hiện tại.</td></tr> : null}</tbody></table></div></section>
  </div></AppShell>;
}
