'use client';

import { createIdempotencyKey } from '@npp/contracts';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

type Product = { id:string; productName:string; sku:string; unitCode:string; allowsFractional:boolean|null };
type Warehouse = { id:string; code:string; name:string };
type Customer = { id:string; code:string; name:string };
type Category = { id:string; code:string; name:string };
type Settings = { defaultSalesChannelId:string|null; defaultTaxMode:'EXCLUSIVE'|'INCLUSIVE'; defaultTaxRate:string };
type OrderLine = { id:string; variantId:string; sku:string; itemName:string; unitCode:string; quantity:string; unitPrice:string; lineTotal:string; taxMode:'EXCLUSIVE'|'INCLUSIVE'; taxRate:string };
type Order = { id:string; number:string|null; status:'draft'|'confirmed'|'closed'|'cancelled'; currentVersionNumber:string; deliveryMode:string; fulfillmentStatus:string; settlementStatus:string; collectionPolicy:string; customerMode:'WALK_IN'|'EXISTING'; customerId:string; total:string; revision:string; customerName:string; warehouseId:string; warehouseName:string; updatedAt:string; versions?:{versionNumber:string;revision:string;lines?:OrderLine[]}[] };
type CartLine = Product & { quantity:string; taxMode:'EXCLUSIVE'|'INCLUSIVE'; taxRate:string };
type Availability = { variantId:string; availabilityStatus:'AVAILABLE'|'UNAVAILABLE'|'NOT_APPLICABLE'; availableQuantity:string|null };
type Bootstrap = { settings:Settings; warehouses:Warehouse[]; customers:Customer[]; categories:Category[]; orders:Order[] };
const money = new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0});
const linesOf=(order:Order|null)=>order?.versions?.find((item)=>item.versionNumber===order.currentVersionNumber)?.lines??order?.versions?.[0]?.lines??[];
const cartFromOrder=(order:Order):CartLine[]=>linesOf(order).map(line=>({id:line.variantId,productName:line.itemName,sku:line.sku,unitCode:line.unitCode,allowsFractional:null,quantity:line.quantity,taxMode:line.taxMode,taxRate:line.taxRate}));
async function api<T>(path:string,init?:RequestInit){const r=await fetch(path,{cache:'no-store',...init,headers:{Accept:'application/json',...(init?.headers??{})}});const p=await r.json().catch(()=>null) as {data?:T;error?:{message?:string}}|null;if(!r.ok||p?.error)throw new Error(p?.error?.message??'Không thể thực hiện thao tác');return p?.data as T;}
function quantity(value:string,fractional:boolean|null){const n=Number(value);if(!Number.isFinite(n)||n<=0)return '1';return fractional?String(Math.min(n,999999)):String(Math.max(1,Math.trunc(n)));}
function label(order:Order){if(order.status==='closed')return order.settlementStatus==='paid'?'Đã hoàn thành · Đã thu đủ':'Đã hoàn thành · Còn phải thu';if(order.status==='confirmed')return order.fulfillmentStatus==='issued'?'Đã Xuất kho':order.fulfillmentStatus==='fulfilled'?'Sẵn sàng hoàn thành':'Đã Chốt';if(order.status==='cancelled')return 'Đã hủy';return 'Đang lập';}

export default function RetailHomePage(){
 const [boot,setBoot]=useState<Bootstrap|null>(null),[order,setOrder]=useState<Order|null>(null),[cart,setCart]=useState<CartLine[]>([]),[available,setAvailable]=useState<Availability[]>([]),[open,setOpen]=useState(false),[search,setSearch]=useState(''),[categoryId,setCategoryId]=useState(''),[products,setProducts]=useState<Product[]>([]),[selected,setSelected]=useState<Map<string,{product:Product;quantity:string}>>(new Map()),[customerMode,setCustomerMode]=useState<'WALK_IN'|'EXISTING'>('WALK_IN'),[customerId,setCustomerId]=useState(''),[warehouseId,setWarehouseId]=useState(''),[policy,setPolicy]=useState('COLLECT_ON_DELIVERY'),[notice,setNotice]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[payment,setPayment]=useState(false),[paid,setPaid]=useState('');
 const keys=useRef(new Map<string,string>());
 const keyFor=useCallback((action:string)=>{const slot=`${action}:${order?.id??'new'}:${order?.revision??'draft'}`;const old=keys.current.get(slot);if(old)return old;const next=createIdempotencyKey(`retail-${action}`);keys.current.set(slot,next);return next;},[order?.id,order?.revision]);
 useEffect(()=>{void api<Bootstrap>('/api/retail/bootstrap').then(data=>{setBoot(data);setWarehouseId(data.warehouses[0]?.id??'');}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!open)return;const c=new AbortController(),t=window.setTimeout(()=>{const params=new URLSearchParams({search,limit:'30',offset:'0'});if(categoryId)params.set('categoryId',categoryId);void api<Product[]>(`/api/retail/products?${params}`,{signal:c.signal}).then(setProducts).catch(e=>!c.signal.aborted&&setError(e.message));},180);return()=>{c.abort();window.clearTimeout(t);};},[open,search,categoryId]);
 useEffect(()=>{if(!order?.id||['closed','cancelled'].includes(order.status))return;void api<Availability[]>(`/api/retail/orders/${order.id}/availability`).then(setAvailable).catch(e=>setError(e.message));},[order?.id,order?.revision,order?.status]);
 const byVariant=useMemo(()=>new Map(available.map(item=>[item.variantId,item])),[available]);const lineItems=linesOf(order);const editable=!order||order.status==='draft';const editingDraft=editable&&cart.length>0;const total=order?Number(order.total||0):0;const totalLabel=(!order&&cart.length)||editingDraft?'Được tính khi lưu':money.format(total);
 function select(product:Product){setSelected(current=>{const next=new Map(current);if(next.has(product.id))next.delete(product.id);else next.set(product.id,{product,quantity:'1'});return next;});}
 function selectedQuantity(id:string,value:string){setSelected(current=>{const next=new Map(current),row=next.get(id);if(row)next.set(id,{...row,quantity:quantity(value,row.product.allowsFractional)});return next;});}
 function addSelected(){setCart(current=>{const next=new Map(current.map(line=>[line.id,line]));for(const row of selected.values()){const old=next.get(row.product.id);next.set(row.product.id,old?{...old,quantity:quantity(String(Number(old.quantity)+Number(row.quantity)),row.product.allowsFractional)}:{...row.product,quantity:row.quantity,taxMode:boot?.settings.defaultTaxMode??'EXCLUSIVE',taxRate:boot?.settings.defaultTaxRate??'0'});}return[...next.values()];});setSelected(new Map());setOpen(false);setNotice('Đã thêm sản phẩm vào giỏ hàng.');}
 function orderPayload(){if(!boot?.settings.defaultSalesChannelId)throw new Error('Công Ty chưa cấu hình kênh bán mặc định.');if(!warehouseId)throw new Error('Hãy chọn kho bán.');if(!cart.length)throw new Error('Hãy chọn ít nhất một sản phẩm.');return{sourceType:'MANUAL',customerMode,...(customerMode==='EXISTING'?{customerId}:{}),warehouseId,salesChannelId:boot.settings.defaultSalesChannelId,deliveryMode:'PICKUP',collectionPolicy:policy,currency:'VND',...(order?{expectedRevision:order.revision}:{}),lines:cart.map(line=>({variantId:line.id,quantity:line.quantity,taxMode:line.taxMode,taxRate:line.taxRate}))};}
 async function save(){setBusy('save');setError(null);try{const next=order?await api<Order>(`/api/retail/orders/${order.id}/draft`,{method:'PUT',headers:{'Content-Type':'application/json','Idempotency-Key':keyFor('save-draft')},body:JSON.stringify(orderPayload())}):await api<Order>('/api/retail/orders',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':keyFor('create-draft')},body:JSON.stringify(orderPayload())});setOrder(next);setCart([]);setNotice(order?'Đã lưu thay đổi đơn.':'Đã lập đơn tại quầy.');}catch(e){setError(e instanceof Error?e.message:'Chưa thể lưu đơn.');}finally{setBusy(null);}}
 async function action(kind:'confirm'|'issue-stock'|'complete'){if(!order)return;setBusy(kind);setError(null);try{const body=kind==='confirm'?{}:{expectedRevision:order.revision};const next=await api<Order>(`/api/retail/orders/${order.id}/${kind}`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':keyFor(kind)},body:JSON.stringify(body)});setOrder(next);setNotice(kind==='confirm'?'Đơn đã được Chốt.':kind==='issue-stock'?'Đã Xuất kho theo luồng Giao tại quầy.':'Đơn đã Hoàn thành.');}catch(e){setError(e instanceof Error?e.message:'Chưa thể thực hiện thao tác.');}finally{setBusy(null);}}
 async function settle(){if(!order)return;setBusy('settlement');try{const next=await api<Order>(`/api/retail/orders/${order.id}/settlement`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':keyFor('settlement')},body:JSON.stringify({expectedRevision:order.revision,paidAmount:paid})});setOrder(next);setPayment(false);setNotice('Đã ghi nhận thanh toán theo khoản phải thu của đơn.');}catch(e){setError(e instanceof Error?e.message:'Chưa thể ghi nhận thanh toán.');}finally{setBusy(null);}}
 return <main className="retail-shell"><header className="retail-header"><div><p className="brand-kicker">HƯNG PHÁT</p><h1>Bán tại quầy</h1><p>{order?`${order.number??'Đơn đang lập'} · ${label(order)}`:'Lập đơn nhanh cho khách nhận hàng tại quầy'}</p></div><form action="/api/auth/logout" method="post"><button className="text-action">Đăng xuất</button></form></header>{error?<p className="notice error" role="alert">{error}</p>:null}{notice?<p className="notice" role="status">{notice}</p>:null}
 <section className="order-card"><div className="section-title"><div><p className="section-kicker">ĐƠN BÁN HÀNG</p><h2>{order?'Giỏ hàng của đơn':'Lên đơn mới'}</h2></div><span className="mode-pill">Giao tại quầy</span></div><div className="order-fields"><label>Khách hàng<select value={customerMode} disabled={!editable} onChange={e=>setCustomerMode(e.target.value as 'WALK_IN'|'EXISTING')}><option value="WALK_IN">Khách lẻ</option><option value="EXISTING">Khách hàng Công Ty</option></select></label>{customerMode==='EXISTING'?<label>Chọn khách hàng<select value={customerId} disabled={!editable} onChange={e=>setCustomerId(e.target.value)}><option value="">Chọn khách hàng</option>{boot?.customers.map(customer=><option key={customer.id} value={customer.id}>{customer.code} · {customer.name}</option>)}</select></label>:null}<label>Kho bán<select value={warehouseId} disabled={!editable} onChange={e=>setWarehouseId(e.target.value)}><option value="">Chọn kho</option>{boot?.warehouses.map(warehouse=><option key={warehouse.id} value={warehouse.id}>{warehouse.code} · {warehouse.name}</option>)}</select></label><label>Thanh toán<select value={policy} disabled={!editable} onChange={e=>setPolicy(e.target.value)}><option value="COLLECT_ON_DELIVERY">Thu khi nhận hàng</option><option value="PREPAID">Đã trả trước</option>{customerMode==='EXISTING'?<><option value="COLLECT_AFTER_DELIVERY">Giao trước, thu sau</option><option value="CREDIT_TERMS">Bán chịu</option></>:null}</select></label></div>{editable?<button className="choose-products" onClick={()=>setOpen(true)}><span aria-hidden="true">＋</span> Chọn sản phẩm</button>:null}
 <div className="cart-list">{order&&!editingDraft?lineItems.map(line=><article className="cart-row" key={line.id}><div className="line-main"><strong>{line.itemName}</strong><span>{line.sku} · {line.unitCode}</span></div><dl><div><dt>Khả dụng</dt><dd>{byVariant.get(line.variantId)?.availabilityStatus==='NOT_APPLICABLE'?'Không áp dụng':byVariant.get(line.variantId)?.availableQuantity??'Đang tải'}</dd></div><div><dt>Số lượng</dt><dd>{line.quantity}</dd></div><div><dt>Đơn giá</dt><dd>{money.format(Number(line.unitPrice))}</dd></div><div><dt>Thành tiền</dt><dd>{money.format(Number(line.lineTotal))}</dd></div></dl></article>):cart.map(line=><article className="cart-row editable" key={line.id}><div className="line-main"><strong>{line.productName}</strong><span>{line.sku} · {line.unitCode}</span></div><dl><div><dt>Khả dụng</dt><dd>{order?(byVariant.get(line.id)?.availabilityStatus==='NOT_APPLICABLE'?'Không áp dụng':byVariant.get(line.id)?.availableQuantity??'Đang tải'):'—'}</dd></div><div><dt>Số lượng</dt><dd><input inputMode="decimal" aria-label={`Số lượng ${line.productName}`} value={line.quantity} onChange={e=>setCart(rows=>rows.map(row=>row.id===line.id?{...row,quantity:quantity(e.target.value,row.allowsFractional)}:row))}/></dd></div><div><dt>Đơn giá</dt><dd>Được tính khi lưu</dd></div></dl><button className="remove-line" onClick={()=>setCart(rows=>rows.filter(row=>row.id!==line.id))} aria-label={`Xóa ${line.productName}`}>×</button></article>)}{(!order||editingDraft)&&!cart.length?<p className="empty-cart">Chưa có sản phẩm. Chọn nhiều sản phẩm rồi thêm vào giỏ trong một lần.</p>:null}</div><footer className="order-total"><span>Tổng tiền</span><strong>{totalLabel}</strong></footer><div className="actions">{editable?<button className="primary-action" disabled={busy!==null} onClick={save}>{busy==='save'?'Đang lưu…':order?'Lưu thay đổi':'Lập đơn'}</button>:null}{order?<><button className="secondary-action" onClick={()=>{window.print();setNotice('Đã mở bản in. Việc in không thay đổi trạng thái đơn.');}}>In phiếu</button>{order.status==='draft'?<button className="primary-action" disabled={busy!==null} onClick={()=>void action('confirm')}>Chốt đơn</button>:null}{order.status==='confirmed'&&!['issued','fulfilled'].includes(order.fulfillmentStatus)?<button className="primary-action" disabled={busy!==null} onClick={()=>void action('issue-stock')}>Xuất kho</button>:null}{order.status==='confirmed'&&['issued','fulfilled'].includes(order.fulfillmentStatus)?<button className="primary-action" disabled={busy!==null} onClick={()=>void action('complete')}>Hoàn thành</button>:null}{order.status==='closed'&&order.settlementStatus!=='paid'?<button className="primary-action" disabled={busy!==null} onClick={()=>{setPaid(order.total);setPayment(true);}}>Thu tiền / Nợ</button>:null}</>:null}</div></section>
 <section className="recent-card"><div className="section-title"><div><p className="section-kicker">GẦN ĐÂY</p><h2>Đơn Giao tại quầy</h2></div></div>{boot?.orders.filter(item=>item.deliveryMode==='PICKUP').slice(0,6).map(item=><button className="recent-row" key={item.id} onClick={()=>{void api<Order>(`/api/retail/orders/${item.id}`).then(next=>{setOrder(next);setCustomerMode(next.customerMode);setCustomerId(next.customerId);setWarehouseId(next.warehouseId);setPolicy(next.collectionPolicy);setCart(next.status==='draft'?cartFromOrder(next):[]);}).catch(e=>setError(e.message));}}><span><strong>{item.number??'Đơn nháp'}</strong><small>{item.customerName}</small></span><em>{label(item)}</em></button>)}</section>
 {open?<section className="product-sheet" role="dialog" aria-modal="true" aria-label="Chọn sản phẩm"><div className="sheet-header"><div><p className="section-kicker">DANH MỤC SẢN PHẨM</p><h2>Chọn nhiều sản phẩm</h2></div><button className="text-action" onClick={()=>setOpen(false)}>Đóng</button></div><div className="search-and-filter"><input className="product-search" autoFocus placeholder="Tìm tên, mã hàng hoặc SKU" value={search} onChange={e=>setSearch(e.target.value)}/><select value={categoryId} onChange={e=>setCategoryId(e.target.value)} aria-label="Lọc nhóm sản phẩm"><option value="">Tất cả nhóm</option>{boot?.categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div className="product-list">{products.map(product=>{const row=selected.get(product.id);return <article className={`product-row ${row?'selected':''}`} key={product.id}><button className="product-select" onClick={()=>select(product)}><span className="product-symbol" aria-hidden="true">{product.productName.slice(0,1)}</span><span><strong>{product.productName}</strong><small>{product.sku} · {product.unitCode}</small></span><b aria-hidden="true">{row?'✓':'+'}</b></button>{row?<label className="temporary-quantity">Số lượng tạm<input inputMode="decimal" value={row.quantity} onChange={e=>selectedQuantity(product.id,e.target.value)}/></label>:null}</article>;})}</div><button className="sheet-submit primary-action" disabled={!selected.size} onClick={addSelected}>Thêm {selected.size} sản phẩm vào đơn</button></section>:null}
 {payment?<section className="dialog-backdrop" role="dialog" aria-modal="true" aria-label="Thu tiền"><div className="payment-dialog"><h2>Thu tiền / Nợ</h2><p>Ghi nhận theo khoản phải thu của đơn, tách riêng khỏi Hoàn thành.</p><label>Số tiền thực thu<input inputMode="numeric" value={paid} onChange={e=>setPaid(e.target.value)}/></label><div><button className="secondary-action" onClick={()=>setPayment(false)}>Để sau</button><button className="primary-action" disabled={busy==='settlement'} onClick={()=>void settle()}>{busy==='settlement'?'Đang ghi nhận…':'Ghi nhận'}</button></div></div></section>:null}</main>;
}
