import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";
import test from "node:test";
import "./vercel-mcp-deployment-control.test.mjs";

const read = (path) => readFile(new URL(path, import.meta.url), "utf8");
const coreConfig = JSON.parse(await read("../../npp-core/web/vercel.json"));
const rootConfig = JSON.parse(await read("../../vercel.json"));
const workflow = await read("../../.github/workflows/vercel-production-manual.yml");
const phase97Manifest = JSON.parse(await read("../../docs/operations/phase-9-7-route-runtime-manifest.json"));
const NPP_PLATFORM_PROJECT_ID = "prj_vFEAzoxesLqNJIfD8uF4q1kytpvk";
const phase97Sources = {"npp-operations":await read("../../npp-core/web/app/components/app-shell-core.tsx"),"mcp-field":await read("../src/ui/shell/navigation.ts"),"admin-mcp-npp":await read("../../admin/web/app/admin-shell.tsx"),delivery:await read("../../delivery/web/app/DeliveryAppFrame.tsx")};
const phase97EnvFiles = {"npp-operations":await read("../../npp-core/web/.env.example"),"mcp-field":await read("../.env.example"),"admin-mcp-npp":await read("../../admin/web/.env.example"),delivery:await read("../../delivery/web/.env.example")};
const EXPECTED_PHASE97_FRONTENDS=[["admin-mcp-npp","binhnxwjfjxm/NPP-Platform","admin/web","admin-mcp-npp","prj_0hp2A8WyUW4zgglShPTzL70hesVC","admin.nguyenlieuhungphat.com"],["customer-ordering","binhnxwjfjxm/nguyenlieuhungphat","customer-ordering","customer-ordering","prj_btLk3p4FhmShgKFdRBMq6ZFOagKe","sales.nguyenlieuhungphat.com"],["delivery","binhnxwjfjxm/NPP-Platform","delivery/web","npp-delivery","prj_aqsb62CiXpN1a1u3vU9P8SOKw2Ux","log.nguyenlieuhungphat.com"],["mcp-field","binhnxwjfjxm/NPP-Platform","mcp","mcp-field","prj_854SWdJeDEOPezAvvTZzTaRvZUSq","mcp.nguyenlieuhungphat.com"],["npp-operations","binhnxwjfjxm/NPP-Platform","npp-core/web","npp-platform",NPP_PLATFORM_PROJECT_ID,"office.nguyenlieuhungphat.com"],["website","binhnxwjfjxm/nguyenlieuhungphat",".","nguyenlieuhungphat","prj_rXqH83GFDHuEGUcQrrv82JBPWnjU","nguyenlieuhungphat.com"]];
const HISTORICAL_NPP_ENV_NAMES=["NEXT_PUBLIC_CORE_API_URL","CORE_API_INTERNAL_URL","CORE_API_SERVER_TOKEN","CORE_WEB_ADMIN_USERNAME","CORE_WEB_ADMIN_PASSWORD","FOUNDATION_TEST_UI_ENABLED","FOUNDATION_R2_TEST_ENABLED"];
const CURRENT_NPP_ENV_NAMES=["NEXT_PUBLIC_CORE_API_URL","CORE_API_INTERNAL_URL","FOUNDATION_TEST_UI_ENABLED","FOUNDATION_R2_TEST_ENABLED"];
const RETIRED_NPP_HUMAN_ENV_NAMES=["CORE_API_SERVER_TOKEN","CORE_WEB_ADMIN_USERNAME","CORE_WEB_ADMIN_PASSWORD"];
const REQUIRED_CUSTOMER_ENV_NAMES=["NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY","NEXT_PUBLIC_CUSTOMER_ORDERING_DATA_MODE","CORE_API_BASE_URL"];
const CURRENT_ADMIN_ENV_NAMES=["CORE_API_INTERNAL_URL","NPP_OPERATIONS_URL"];
const RETIRED_ADMIN_HUMAN_ENV_NAMES=["CORE_API_SERVER_TOKEN","CORE_WEB_ADMIN_USERNAME","CORE_WEB_ADMIN_PASSWORD"];
const CURRENT_DELIVERY_ENV_NAMES=["CORE_API_INTERNAL_URL","NEXT_PUBLIC_APP_LOGO_URL"];
const RETIRED_DELIVERY_HUMAN_ENV_NAMES=["DELIVERY_CORE_API_TOKEN","DELIVERY_WEB_USERS_JSON","DELIVERY_SETUP_MODE"];
function envNames(source){return source.split(/\r?\n/).map((line)=>line.trim()).filter((line)=>/^[A-Z0-9_]+=/.test(line)).map((line)=>line.slice(0,line.indexOf("=")));}
function assertNoSensitiveManifestValues(value,path="manifest"){if(Array.isArray(value))return value.forEach((item,index)=>assertNoSensitiveManifestValues(item,`${path}[${index}]`));if(!value||typeof value!=="object"){if(typeof value==="string"&&!path.includes(".productionRelevantEnvNames["))assert.doesNotMatch(value,/postgres(?:ql)?:\/\/|vcp_|cfat_|cfut_|os_v2_|sb_secret_/i,path);return;}for(const[key,child]of Object.entries(value)){const childPath=`${path}.${key}`;if(!childPath.includes(".productionRelevantEnvNames"))assert.doesNotMatch(key,/(?:password|secret|token|credential|database.?url)/i,childPath);assertNoSensitiveManifestValues(child,childPath);}}
async function collectMcpSourceFiles(directoryUrl){const files=[];for(const entry of await readdir(directoryUrl,{withFileTypes:true})){if(["node_modules",".next","coverage"].includes(entry.name))continue;const child=new URL(`${entry.name}${entry.isDirectory()?"/":""}`,directoryUrl);if(entry.isDirectory())files.push(...await collectMcpSourceFiles(child));else if(/\.(?:ts|tsx|js|mjs|json)$/.test(entry.name)&&!/\.test\./.test(entry.name))files.push(child);}return files;}

test("Vercel uses the NPP Core web package as its project root",()=>{assert.equal(coreConfig.builds,undefined);assert.equal(coreConfig.routes,undefined);assert.equal(coreConfig.framework,undefined);assert.equal(coreConfig.outputDirectory,undefined);});
test("legacy repository-root config is inert and locked",()=>{assert.equal(rootConfig.git?.deploymentEnabled,false);assert.equal(rootConfig.builds,undefined);assert.equal(rootConfig.routes,undefined);assert.equal(rootConfig.build,undefined);});
test("automatic Core Vercel deployments stay locked by default",()=>{assert.equal(coreConfig.git?.deploymentEnabled,false);assert.match(workflow,/^\s{2}workflow_dispatch:\s*$/m);assert.match(workflow,/^\s{2}issue_comment:\s*$/m);assert.doesNotMatch(workflow,/^\s{2}(?:push|pull_request):\s*$/m);});
test("Core comment deployment requires its exact Issue #5 command",()=>{assert.match(workflow,/github\.event\.issue\.number == 5/);assert.match(workflow,/trimmed_comment/);assert.match(workflow,/'\/deploy-vercel-production'/);assert.doesNotMatch(workflow,/\/deploy-vercel-mcp-production/);assert.match(workflow,/\["binhnxwjfjxm","khuongbinhinfo-a11y"\]/);assert.match(workflow,/github\.actor/);});
test("Core deployment is pinned to the npp-platform project",()=>{assert.match(workflow,/VERCEL_ORG_ID: team_hBA8rX68UHC8ogvREkOyQlJ2/);assert.match(workflow,new RegExp(`VERCEL_PROJECT_ID: ${NPP_PLATFORM_PROJECT_ID}`));assert.match(workflow,/Verify Vercel project link/);assert.match(workflow,/linked\.projectId !== process\.env\.VERCEL_PROJECT_ID/);assert.match(workflow,/linked\.settings\?\.rootDirectory !== 'npp-core\/web'/);assert.doesNotMatch(workflow,/vars\.VERCEL_MCP_PROJECT_ID/);});
test("Core deployment installs dependencies and deploys only Core",()=>{for(const marker of[/permissions:\s*\n\s+contents: read/,/Install workspace dependencies/,/run: npm ci/,/vercel@latest pull/,/vercel@latest deploy/,/--prod/,/secrets\.VERCEL_TOKEN/,/git fetch origin main --depth=1/,/git rev-parse origin\/main/])assert.match(workflow,marker);assert.doesNotMatch(workflow,/working-directory: mcp\/|heroku container:push|heroku container:release|git push heroku|deploymentEnabled: true|git push origin HEAD:main|vcp_[A-Za-z0-9_-]+/);});
test("Core production deployment performs workforce-session smoke checks",()=>{assert.match(workflow,/assert_status \/ 302 307 401/);assert.match(workflow,/assert_status \/login 200/);assert.match(workflow,/assert_status \/dashboard 302 307 401/);assert.match(workflow,/assert_status \/api\/customers 401/);assert.match(workflow,/Welcome to Hung Phat Operations\./);assert.match(workflow,/\/_next\/static\//);assert.match(workflow,/DEPLOYED_SHA=/);assert.match(workflow,/DEPLOYED_URL=/);assert.doesNotMatch(workflow,/CORE_WEB_ADMIN_USERNAME|CORE_WEB_ADMIN_PASSWORD|CORE_API_SERVER_TOKEN|Authorization: Basic/);});
test("Phase 9.7 manifest locks the exact six frontend identities",()=>{assert.equal(phase97Manifest.phase,"9.7");assert.equal(phase97Manifest.issue,394);const actual=phase97Manifest.frontends.map((item)=>[item.id,item.repository,item.sourceRoot,item.vercel.projectName,item.vercel.projectId,item.expectedDomain]).sort((a,b)=>a[0].localeCompare(b[0]));assert.deepEqual(actual,EXPECTED_PHASE97_FRONTENDS);});
test("Phase 9.7 source route audit has no orphan top-level business route",()=>{for(const frontend of phase97Manifest.frontends){assert.equal(frontend.routeAudit.status,"PASS",frontend.id);assert.equal(frontend.routeAudit.orphanTopLevelCount,0,frontend.id);}for(const[id,source]of Object.entries(phase97Sources)){const frontend=phase97Manifest.frontends.find((item)=>item.id===id);assert.ok(frontend,id);for(const href of frontend.routeAudit.entryHrefs)if(href!=="/")assert.ok(source.includes(href),`${id} missing navigation evidence for ${href}`);}});
test("Phase 9.7 external frontend evidence is pinned to exact GitHub commits",()=>{assert.match(phase97Manifest.auditBaselines.websiteCustomer.mainCommit,/^[0-9a-f]{40}$/);assert.match(phase97Manifest.auditBaselines.websiteCustomer.treeSha,/^[0-9a-f]{40}$/);assert.match(phase97Manifest.auditBaselines.websiteCustomer.phase97HeadCommit,/^[0-9a-f]{40}$/);for(const id of["website","customer-ordering"]){const frontend=phase97Manifest.frontends.find((item)=>item.id===id);assert.equal(frontend.repository,"binhnxwjfjxm/nguyenlieuhungphat");assert.equal(frontend.routeAudit.evidenceMode,"EXTERNAL_GITHUB_AUDIT");}});
test("Phase 9.7 env evidence stays historical while Phase 9.9 NPP/Admin/Delivery supersessions are explicit",()=>{for(const[id,source]of Object.entries(phase97EnvFiles)){const frontend=phase97Manifest.frontends.find((item)=>item.id===id);assert.ok(frontend,id);if(["npp-operations","admin-mcp-npp","delivery"].includes(id))continue;for(const name of frontend.productionRelevantEnvNames)assert.match(source,new RegExp(`^${name}=`,`m`),`${id}:${name}`);}const historicalNpp=phase97Manifest.frontends.find((item)=>item.id==="npp-operations");const currentNpp=phase97EnvFiles["npp-operations"];assert.ok(historicalNpp);assert.deepEqual([...historicalNpp.productionRelevantEnvNames].sort(),[...HISTORICAL_NPP_ENV_NAMES].sort());for(const name of RETIRED_NPP_HUMAN_ENV_NAMES)assert.doesNotMatch(currentNpp,new RegExp(`^${name}=`,`m`));for(const name of CURRENT_NPP_ENV_NAMES)assert.match(currentNpp,new RegExp(`^${name}=`,`m`));const currentNppNames=envNames(currentNpp);for(const name of CURRENT_NPP_ENV_NAMES)assert.ok(currentNppNames.includes(name));for(const name of RETIRED_NPP_HUMAN_ENV_NAMES)assert.ok(!currentNppNames.includes(name));const historicalAdmin=phase97Manifest.frontends.find((item)=>item.id==="admin-mcp-npp");const currentAdmin=phase97EnvFiles["admin-mcp-npp"];for(const name of RETIRED_ADMIN_HUMAN_ENV_NAMES){assert.ok(historicalAdmin.productionRelevantEnvNames.includes(name));assert.doesNotMatch(currentAdmin,new RegExp(`^${name}=`,`m`));}for(const name of CURRENT_ADMIN_ENV_NAMES)assert.match(currentAdmin,new RegExp(`^${name}=`,`m`));assert.deepEqual(envNames(currentAdmin).sort(),[...CURRENT_ADMIN_ENV_NAMES].sort());const historicalDelivery=phase97Manifest.frontends.find((item)=>item.id==="delivery");const currentDelivery=phase97EnvFiles.delivery;for(const name of RETIRED_DELIVERY_HUMAN_ENV_NAMES){assert.ok(historicalDelivery.productionRelevantEnvNames.includes(name));assert.doesNotMatch(currentDelivery,new RegExp(`^${name}=`,`m`));}for(const name of CURRENT_DELIVERY_ENV_NAMES)assert.match(currentDelivery,new RegExp(`^${name}=`,`m`));assert.deepEqual(envNames(currentDelivery).sort(),[...CURRENT_DELIVERY_ENV_NAMES].sort());const customer=phase97Manifest.frontends.find((item)=>item.id==="customer-ordering");assert.deepEqual([...customer.productionRelevantEnvNames].sort(),[...REQUIRED_CUSTOMER_ENV_NAMES].sort());assert.equal(customer.logoAsset.mode,"LOCAL_PUBLIC_ASSET");assert.equal(customer.logoAsset.path,"/logo-transparent.png");assert.equal(customer.logoAsset.externalEnvironmentVariableRequired,false);assertNoSensitiveManifestValues(phase97Manifest);});
test("Phase 9.7 Vercel evidence keeps deployment drift explicit",()=>{for(const frontend of phase97Manifest.frontends){const deployment=frontend.vercel.latestProductionDeployment;assert.equal(deployment.state,"READY",frontend.id);assert.equal(deployment.target,"production",frontend.id);assert.equal(deployment.githubCommitRef,"main",frontend.id);assert.equal(`binhnxwjfjxm/${deployment.githubRepository}`,frontend.repository,frontend.id);assert.equal(frontend.vercel.customDomainAssignmentStatus,"VERIFIED_PROJECT_META",frontend.id);assert.ok(frontend.vercel.assignedDomains.includes(frontend.expectedDomain),frontend.id);}const nppMain=phase97Manifest.auditBaselines.nppPlatform.mainCommit;const externalMain=phase97Manifest.auditBaselines.websiteCustomer.mainCommit;assert.ok(phase97Manifest.frontends.some((item)=>item.repository.endsWith("/NPP-Platform")&&item.vercel.latestProductionDeployment.githubCommitSha!==nppMain));assert.ok(phase97Manifest.frontends.some((item)=>item.id==="website"&&item.vercel.latestProductionDeployment.githubCommitSha!==externalMain));});
test("Phase 9.7 records provider evidence without claiming undeployed source is production-ready",()=>{for(const key of["routeReachabilitySource","providerProjectIdentity","providerRepositoryAndProductionBranch","providerRootDirectory","providerEnvironmentNamePresence","providerCustomDomainAssignment","providerAutoDeployOff","mcpBackendApiBaseProductionValue","dnsState"])assert.equal(phase97Manifest.gate[key],"PASS",key);assert.equal(phase97Manifest.gate.dnsSwitch,"NOT_REQUIRED_ALREADY_CORRECT");assert.equal(phase97Manifest.gate.environmentSwitch,"CONFIGURED_PENDING_DEPLOY");assert.equal(phase97Manifest.gate.sourceMergePending,true);assert.equal(phase97Manifest.gate.productionDeployPending,true);assert.equal(phase97Manifest.gate.phase97ProductionReady,false);assert.deepEqual(phase97Manifest.productionMutations,{vercelDeployment:false,environmentChange:false,domainChange:false,dnsSwitch:false,backendDeploy:false,databaseMigration:false});});
test("Phase 9.7 MCP source keeps backend API routing server-owned",async()=>{const serverEnv=await read("../src/server/env.ts");const nextConfig=await read("../next.config.mjs");const mcp=phase97Manifest.frontends.find((item)=>item.id==="mcp-field");assert.equal(mcp.backendTarget.expectedService,"hung-phat-mcp");assert.equal(mcp.backendTarget.apiBaseVariable,"BACKEND_API_BASE_URL");assert.equal(mcp.backendTarget.productionValueStatus,"VERIFIED_OWNER_PROVIDER");assert.match(serverEnv,/required\("BACKEND_API_BASE_URL"\)/);assert.match(nextConfig,/requiredBuildEnv\("BACKEND_API_BASE_URL"\)/);const scanned=[...await collectMcpSourceFiles(new URL("../src/",import.meta.url)),new URL("../next.config.mjs",import.meta.url),new URL("../package.json",import.meta.url),new URL("../tsconfig.json",import.meta.url)];for(const file of scanned)assert.doesNotMatch(await readFile(file,"utf8"),/NEXT_PUBLIC_BACKEND_API_BASE_URL/,file.pathname);});
