'use client';

import { AppShell } from '../../components/app-shell-core';
import styles from './data-exchange.module.css';
import {
  type Tab, type Category, type Channel, type CustomerGroup, type Customer, type Balance, type QuotationRow, type MovementView, type PriceList,
  PRODUCT_COLUMNS,
} from './data-exchange-model';
import { scopeKey, trimDecimal, scaled12 } from './data-exchange-file-utils';

type WarehouseOption = { id: string; code: string; name: string };
type DataExchangeViewContext = Record<string, any> & {
  warehouses: WarehouseOption[];
  categories: Category[];
  channels: Channel[];
  groups: CustomerGroup[];
  customers: Customer[];
  priceLists: PriceList[];
  quotationRows: QuotationRow[];
  balances: Balance[];
  movementRows: MovementView[];
};

export function DataExchangeView({ ctx }: { ctx: DataExchangeViewContext }) {
  const {
    tab, setTab, setError, setMessage, setPendingImport, busy, setBusy, error, message, fileRefs, fileInput, productTemplate, productExport, columnChooser,
    productColumns, setProductColumns, previewTable, pricingExport, priceLists, pricingPriceListId, setPricingPriceListId, stocktakeExport, stocktakeWarehouse,
    setStocktakeWarehouse, warehouses, buildQuotation, quotationExport, quotationRows, quotationScope, setQuotationScope, quotationCategory,
    setQuotationCategory, categories, quotationSkus, setQuotationSkus, quotationContext, setQuotationContext, channels, groups, customers,
    loadMovements, selectedBalanceKey, setSelectedBalanceKey, setMovementRows, balances, selectedBalance, movementRows, refreshReferenceData, begin, fail,
  } = ctx;
  const actions = <div className={styles.headerActions}><a className={styles.secondaryButton} href="/operations/import-export-history">Lịch sử nhập / xuất</a><button className={styles.secondaryButton} type="button" onClick={() => { begin(); refreshReferenceData().then(() => setMessage('Đã cập nhật dữ liệu nền.')).catch(fail).finally(() => setBusy(false)); }} disabled={busy}>Làm mới</button></div>;
  return <AppShell kicker="Dữ liệu vận hành" title="Nhập / xuất dữ liệu & báo giá" subtitle="Nhập, kiểm tra và xuất dữ liệu theo từng nghiệp vụ. Tên cột và lựa chọn đều dùng ngôn ngữ vận hành; hệ thống tự chuyển sang định dạng kỹ thuật ở phía sau." actions={actions}>
    <div className={styles.page} data-testid="phase-10-4-data-exchange">
      <nav className={styles.tabs} aria-label="Nhóm dữ liệu">{([['products', 'Sản phẩm / SKU'], ['pricing', 'Giá bán'], ['stocktake', 'Kiểm kê'], ['quotation', 'Báo giá'], ['movements', 'Biến động kho']] as Array<[Tab, string]>).map(([key, label]) => <button key={key} type="button" className={tab === key ? styles.activeTab : ''} onClick={() => { setTab(key); setError(''); setMessage(''); setPendingImport(null); }}>{label}</button>)}</nav>
      {error ? <div className={styles.error} role="alert"><strong>Chưa thể thực hiện.</strong><span>{error}</span></div> : null}{message ? <div className={styles.success} role="status">{message}</div> : null}

      {tab === 'products' ? <section className={styles.panel}><div className={styles.panelTitle}><div><h2>Sản phẩm / SKU</h2><p>Nhập hoặc xuất nhiều sản phẩm và SKU cùng lúc. Sau khi chọn file, hệ thống luôn cho xem trước và sửa các lựa chọn về đơn vị, lô, hạn sử dụng và vị trí kho trước khi ghi dữ liệu.</p></div><div className={styles.buttonRow}>
        {fileInput('products', '.xlsx,.csv', 'products')}<button type="button" className={styles.primaryButton} onClick={() => fileRefs.current.products?.click()} disabled={busy}>Chọn file để nhập</button>
        <button type="button" className={styles.secondaryButton} onClick={() => void productTemplate('xlsx')} disabled={busy}>Tải mẫu Excel</button><button type="button" className={styles.secondaryButton} onClick={() => void productTemplate('csv')} disabled={busy}>Tải mẫu CSV</button>
        <button type="button" className={styles.secondaryButton} onClick={() => void productExport('xlsx')} disabled={busy}>Xuất Excel</button><button type="button" className={styles.secondaryButton} onClick={() => void productExport('csv')} disabled={busy}>Xuất CSV</button>
      </div></div>{columnChooser(PRODUCT_COLUMNS, productColumns, setProductColumns)}<div className={styles.guardrail}><strong>Cách khai báo SKU</strong><span>Mỗi SKU chọn Đơn vị tính và Hệ số quy đổi. SKU dùng làm đơn vị tồn chuẩn có hệ số = 1; tại SKU này chọn thêm Có/Không quản lý theo lô, cách quản lý hạn sử dụng và có bắt buộc vị trí kho hay không.</span></div><p className={styles.note}>Khi cập nhật sản phẩm đã có, file cần chứa đầy đủ các SKU đang sử dụng của sản phẩm đó để tránh vô tình bỏ sót quy cách.</p>{previewTable()}</section> : null}

      {tab === 'pricing' ? <section className={styles.panel}><div className={styles.panelTitle}><div><h2>Cập nhật giá bán theo SKU</h2><p>Chọn một bảng giá hoặc chương trình đang hoạt động. File chỉ cần đúng 2 cột: <strong>SKU</strong> và <strong>Giá bán (VND)</strong>. SKU là khóa tra cứu; cùng một file dùng được cho SKU đã có giá để cập nhật và SKU chưa có giá để tạo mới.</p></div><div className={styles.buttonRow}>{fileInput('pricing', '.xlsx,.csv', 'pricing')}<button type="button" className={styles.primaryButton} onClick={() => fileRefs.current.pricing?.click()} disabled={busy || !pricingPriceListId}>Chọn file SKU | Giá</button><button type="button" className={styles.secondaryButton} onClick={() => void pricingExport('xlsx')} disabled={busy || !pricingPriceListId}>Tải/Xuất Excel 2 cột</button><button type="button" className={styles.secondaryButton} onClick={() => void pricingExport('csv')} disabled={busy || !pricingPriceListId}>Tải/Xuất CSV 2 cột</button></div></div><label className={styles.field}>Bảng giá nền cần cập nhật / chương trình CTKM<select value={pricingPriceListId} onChange={(event) => { setPricingPriceListId(event.target.value); setPendingImport(null); setError(''); setMessage(''); }}><option value="">Chọn bảng giá / chương trình</option>{priceLists.filter((list) => list.is_active).map((list) => <option key={list.id} value={list.id}>{list.code} · {list.name}</option>)}</select></label><div className={styles.guardrail}><strong>File luôn chỉ có SKU và Giá bán; mọi ngữ cảnh nằm ngoài file.</strong><span>Khi xác nhận, backend đối chiếu SKU + bảng giá/chương trình + điều kiện mặc định. Dòng tương ứng đã có thì cập nhật; chưa có thì tạo FIXED_PRICE mới. Hiệu lực, kênh bán, nhóm khách hoặc khách hàng lấy từ bảng giá/chương trình đã chọn, không bắt người dùng nhét thêm cột kỹ thuật vào file.</span></div>{previewTable()}</section> : null}

      {tab === 'stocktake' ? <section className={styles.panel}><div className={styles.panelTitle}><div><h2>Nhập số kiểm kê thực tế</h2><p>Chọn kho, tải file kiểm kê, điền số đếm thực tế rồi nhập lại. Hệ thống chỉ tạo phiếu kiểm kê nháp; tồn kho chưa thay đổi cho đến khi phiếu được duyệt và ghi sổ.</p></div><div className={styles.buttonRow}>{fileInput('stocktake', '.xlsx,.csv', 'stocktake')}<button type="button" className={styles.primaryButton} onClick={() => fileRefs.current.stocktake?.click()} disabled={busy}>Chọn file số đếm</button><button type="button" className={styles.secondaryButton} onClick={() => void stocktakeExport('xlsx')} disabled={busy}>Tải mẫu Excel</button><button type="button" className={styles.secondaryButton} onClick={() => void stocktakeExport('csv')} disabled={busy}>Tải mẫu CSV</button></div></div><label className={styles.field}>Kho kiểm kê<select value={stocktakeWarehouse} onChange={(event) => setStocktakeWarehouse(event.target.value)}><option value="">Chọn kho</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.code} · {warehouse.name}</option>)}</select></label><div className={styles.guardrail}><strong>Kiểm kê không thay đổi tồn ngay.</strong><span>Số đếm thực tế → tạo phiếu kiểm kê nháp → gửi duyệt → duyệt → ghi sổ chênh lệch. Chưa gửi duyệt, chưa ghi sổ tồn.</span><a href="/inventory/stocktakes">Mở màn Kiểm kê kho</a></div>{previewTable()}</section> : null}

      {tab === 'quotation' ? <section className={styles.panel}><div className={styles.panelTitle}><div><h2>Báo giá</h2><p>Chọn phạm vi hàng hóa và khách hàng; hệ thống tự tìm mức giá đang áp dụng cho từng SKU.</p></div><div className={styles.buttonRow}><button type="button" className={styles.primaryButton} onClick={() => void buildQuotation()} disabled={busy}>Tính báo giá</button><button type="button" className={styles.secondaryButton} onClick={() => void quotationExport('xlsx')} disabled={busy || !quotationRows.length}>Xuất Excel</button><button type="button" className={styles.secondaryButton} onClick={() => void quotationExport('csv')} disabled={busy || !quotationRows.length}>Xuất CSV</button></div></div><div className={styles.formGrid}>
        <label className={styles.field}>Phạm vi<select value={quotationScope} onChange={(event) => setQuotationScope(event.target.value as 'all' | 'category' | 'sku')}><option value="all">Tất cả SKU đang bán</option><option value="category">Theo ngành / nhóm</option><option value="sku">Danh sách SKU</option></select></label>
        {quotationScope === 'category' ? <label className={styles.field}>Ngành / nhóm<select value={quotationCategory} onChange={(event) => setQuotationCategory(event.target.value)}><option value="">Chọn nhóm</option>{categories.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label> : null}
        {quotationScope === 'sku' ? <label className={`${styles.field} ${styles.span2}`}>SKU<input value={quotationSkus} onChange={(event) => setQuotationSkus(event.target.value)} placeholder="SKU001, SKU002..." /></label> : null}
        <label className={styles.field}>Kênh bán<select value={quotationContext.channelId} onChange={(event) => setQuotationContext({ ...quotationContext, channelId: event.target.value })}><option value="">Không chọn</option>{channels.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label>
        <label className={styles.field}>Nhóm khách<select value={quotationContext.customerGroupId} onChange={(event) => setQuotationContext({ ...quotationContext, customerGroupId: event.target.value })}><option value="">Không chọn</option>{groups.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label>
        <label className={styles.field}>Khách hàng<select value={quotationContext.customerId} onChange={(event) => setQuotationContext({ ...quotationContext, customerId: event.target.value })}><option value="">Không chọn</option>{customers.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label>
        <label className={styles.field}>Số lượng<input inputMode="decimal" value={quotationContext.quantity} onChange={(event) => setQuotationContext({ ...quotationContext, quantity: event.target.value })} /></label></div>
        {quotationRows.length ? <div className={styles.tableWrap}><table><thead><tr><th>SKU</th><th>Sản phẩm</th><th>SL</th><th>Giá áp dụng</th><th>Thành tiền</th><th>Bảng giá</th></tr></thead><tbody>{quotationRows.map((row) => <tr key={row.sku}><td><strong>{row.sku}</strong><small>{row.name}</small></td><td>{row.product}</td><td>{row.quantity}</td><td>{row.finalPrice || '—'}</td><td>{row.lineTotal || '—'}</td><td>{row.priceListCode || '—'}</td></tr>)}</tbody></table></div> : null}</section> : null}

      {tab === 'movements' ? <section className={styles.panel}><div className={styles.panelTitle}><div><h2>Biến động tồn kho theo SKU</h2><p>Chọn một dòng tồn để xem từng lần nhập, xuất hoặc điều chỉnh và số tồn sau mỗi lần.</p></div><button type="button" className={styles.primaryButton} onClick={() => void loadMovements()} disabled={busy}>Xem biến động</button></div><label className={styles.field}>Dòng tồn<select value={selectedBalanceKey} onChange={(event) => { setSelectedBalanceKey(event.target.value); setMovementRows([]); }}><option value="">Chọn kho / vị trí / SKU / lô</option>{balances.map((item) => { const key = scopeKey(item.warehouse_code, item.location_code, item.base_sku, item.lot_code); return <option key={key} value={key}>{item.warehouse_code} · {item.location_code || 'Không vị trí'} · {item.base_sku}{item.lot_code ? ` · ${item.lot_code}` : ''} · tồn {trimDecimal(item.on_hand_quantity)}</option>; })}</select></label>
        {selectedBalance ? <div className={styles.balanceSummary}><span>Tồn hiện tại <strong>{trimDecimal(selectedBalance.on_hand_quantity)}</strong></span><span>Đang giữ <strong>{trimDecimal(selectedBalance.reserved_quantity)}</strong></span><span>Khả dụng <strong>{trimDecimal(selectedBalance.available_quantity)}</strong></span></div> : null}
        {movementRows.length ? <div className={styles.tableWrap}><table><thead><tr><th>Thời gian</th><th>Chứng từ</th><th>Loại</th><th>Biến động</th><th>Tồn sau</th></tr></thead><tbody>{movementRows.map((row) => <tr key={`${row.movement_id}:${row.source_line_reference ?? row.base_quantity_delta}`}><td>{new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short', timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date(row.posted_at))}</td><td>{row.source_document_number || row.document_number || row.source_document_type || '—'}</td><td>{row.movement_type}</td><td className={scaled12(row.base_quantity_delta) >= 0n ? styles.positive : styles.negative}>{scaled12(row.base_quantity_delta) >= 0n ? '+' : ''}{trimDecimal(row.base_quantity_delta)}</td><td>{trimDecimal(row.stockAfter)}</td></tr>)}</tbody></table></div> : null}</section> : null}
    </div>
  </AppShell>;
}
