import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8');
const readRepo = (path) => readFile(new URL(`../../../${path}`, import.meta.url), 'utf8');
const readWorkspace = async () => (await Promise.all([read('app/page.tsx'), read('app/retail-workspace.tsx')])).join('\n');

test('sau Lô 7 giữ mã lỗi và dữ liệu conflict để đồng bộ revision đúng đơn', async () => { const page = await readWorkspace(); assert.match(page, /class RetailApiError extends Error/); assert.match(page, /this\.code = error\?\.code/); assert.match(page, /this\.details = error\?\.details/); assert.match(page, /operationKeyFor\('issue-stock', 'current-order'\)/); assert.match(page, /api<Order>\(`\/api\/retail\/orders\/\$\{order\.id\}`\)/); assert.match(page, /Đã nạp dữ liệu mới nhất/); });

test('retry Xuất kho giữ nguyên canonical Idempotency-Key khi chỉ đổi revision', async () => { const page = await readWorkspace(); const conflict = page.slice(page.indexOf("if (kind === 'issue-stock' && isRevisionConflict")); assert.doesNotMatch(conflict.slice(0, conflict.indexOf('setError')), /forgetOperationKey/); assert.match(page, /if \(kind === 'issue-stock'\) forgetOperationKey\('issue-stock', 'current-order'\)/); });

test('Khả dụng khi sửa đơn dùng preview theo kho và loại chính đơn hiện tại', async () => { const [page, gateway, route, service] = await Promise.all([readWorkspace(), read('app/api/retail/[...segments]/route.ts'), readRepo('npp-core/api/src/routes/retail-catalog.js'), readRepo('npp-core/api/src/services/retail-catalog.js')]); assert.match(page, /\/api\/retail\/availability/); assert.match(page, /salesOrderId: order\.id, warehouseId, variantIds/); assert.match(page, /availabilityLoading/); assert.match(gateway, /path: '\/api\/retail\/availability'/); assert.match(route, /previewRetailAvailability/); assert.match(service, /String\(sourceLines\[0\]\.warehouse_id\) !== warehouseId/); assert.match(service, /RETAIL_AVAILABILITY_WAREHOUSE_MISMATCH/); assert.match(service, /excludingSalesOrderId = salesOrderId/); assert.match(service, /getWarehouseAvailableQuantity/); });

test('điều hướng Retail có bốn mục và đăng xuất không quay lại lịch sử trình duyệt', async () => { const page = await readWorkspace(); assert.match(page, /type RetailTab = 'home' \| 'entry' \| 'orders' \| 'account'/); assert.match(page, />Trang chủ<\/button>/); assert.match(page, />Lên đơn<\/button>/); assert.match(page, />Đơn hàng<\/button>/); assert.match(page, />Tài khoản<\/button>/); assert.match(page, /action="\/api\/auth\/logout"/); assert.doesNotMatch(page, /window\.history\.back/); });

test('in phiếu đọc mẫu Công Ty và hỗ trợ A4 A5 80mm 58mm không đưa ảnh vào chứng từ', async () => { const [page, gateway] = await Promise.all([readWorkspace(), read('app/api/retail/[...segments]/route.ts')]); assert.match(page, /\/api\/retail\/print-templates/); assert.match(gateway, /\/api\/document-print-templates/); assert.match(page, /type PrintPaper = 'A4' \| 'A5' \| '80mm' \| '58mm'/); assert.match(page, /visiblePrintFields\.has\('line_item'\)/); assert.match(page, /Máy in Wi-Fi được chọn trong hộp thoại in của thiết bị/); const printSlice = page.slice(page.indexOf('className="print-document"')); assert.doesNotMatch(printSlice, /productPicture|product-photo/); });

test('ba thao tác đơn đúng thứ tự, giữ một hàng trên mobile và không che tổng tiền', async () => { const [page, css] = await Promise.all([readWorkspace(), read('app/retail-lot7.css')]); const actions = page.slice(page.indexOf('className="order-action-bar"')); assert.ok(actions.indexOf('✎ Sửa đơn') < actions.indexOf('▣ In phiếu')); assert.ok(actions.indexOf('▣ In phiếu') < actions.indexOf('⌑ Xuất kho')); assert.match(css, /\.retail-lot7 \.order-action-bar \{[^}]*grid-template-columns: repeat\(3,minmax\(0,1fr\)\)/); assert.match(css, /@media \(max-width: 640px\)[\s\S]*?\.retail-lot7 \.order-action-bar \{[^}]*grid-template-columns: repeat\(3,minmax\(0,1fr\)\)/); assert.match(css, /padding-bottom: calc\(190px \+ env\(safe-area-inset-bottom\)\)/); });

test('ảnh sản phẩm có fallback thật khi R2 lỗi', async () => { const page = await readWorkspace(); assert.match(page, /className="product-visual"/); assert.match(page, /event\.currentTarget\.hidden = true/); assert.match(page, /product-fallback/); });

test('lưu sửa thành công không bị báo thất bại chỉ vì bước GET đồng bộ sau đó lỗi', async () => { const page = await readWorkspace(); assert.match(page, /setNotice\('Đã lưu thay đổi đơn và giữ nguyên trạng thái Đã chốt\.'\)/); assert.match(page, /api<Order>\(`\/api\/retail\/orders\/\$\{next\.id\}`\)\.then\(setOrder\)\.catch\(\(\) => undefined\)/); });
