"use client";
import { useMemo,useState } from "react";
import { KpiCard } from "@/ui/cards/KpiCard";
import { FilterBar } from "@/ui/layout/FilterBar";
import { McpButton,McpCard,McpPageHeader,McpSheet,McpStatusPill } from "@/ui/foundation";
import { AppShell } from "@/ui/shell/AppShell";
import { DataTable,type DataTableColumn } from "@/ui/table/DataTable";
import type { ActionItem,ActionKpi,ActionPriority,ActionSource,ActionStatus } from "./actions.types";
import styles from "./ActionsClientPage.module.css";
function priorityLabel(p:ActionPriority){return p==="high"?"Cao":p==="medium"?"Vừa":"Thấp"} function priorityTone(p:ActionPriority){return p==="high"?"danger" as const:p==="medium"?"warning" as const:"neutral" as const}
function statusLabel(s:ActionStatus){return s==="todo"?"Cần làm":s==="doing"?"Đang làm":s==="done"?"Đã xong":"Bị chặn"} function statusTone(s:ActionStatus){return s==="done"?"success" as const:s==="doing"?"warning" as const:s==="blocked"?"danger" as const:"neutral" as const}
function sourceLabel(s:ActionSource){return s==="session"?"Phiên đi tuyến":s==="field_check"?"Ghi nhận / thử sản phẩm":s==="order"?"Đơn hàng":"Thủ công"}
function dateKey(v:string){const r=v.trim(),i=r.match(/^(\d{4})-(\d{2})-(\d{2})/);if(i)return `${i[1]}-${i[2]}-${i[3]}`;const x=r.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);return x?`${x[3]}-${x[2].padStart(2,"0")}-${x[1].padStart(2,"0")}`:null}
function today(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),v=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${v.year}-${v.month}-${v.day}`} function overdue(i:ActionItem){const d=dateKey(i.dueDate);return i.status!=="done"&&Boolean(d&&d<today())}
function columns(open:(i:ActionItem)=>void):DataTableColumn<ActionItem>[]{return[{key:"title",header:"Việc cần làm",render:r=>r.title},{key:"account",header:"Điểm bán",render:r=>r.accountName},{key:"route",header:"Tuyến",render:r=>r.routeName},{key:"owner",header:"Phụ trách",render:r=>r.owner},{key:"source",header:"Nguồn",render:r=><McpStatusPill tone="neutral">{sourceLabel(r.source)}</McpStatusPill>},{key:"priority",header:"Ưu tiên",render:r=><McpStatusPill tone={priorityTone(r.priority)}>{priorityLabel(r.priority)}</McpStatusPill>},{key:"status",header:"Trạng thái",render:r=><McpStatusPill tone={statusTone(r.status)}>{statusLabel(r.status)}</McpStatusPill>},{key:"due",header:"Hạn",render:r=>r.dueDate},{key:"detail",header:"",render:r=><McpButton variant="secondary" onClick={()=>open(r)}>Xem</McpButton>}]}
function Mobile({item,onOpen}:{item:ActionItem;onOpen:(i:ActionItem)=>void}){const late=overdue(item);return <McpCard className={styles.mobileCard} data-plan-mobile-card><div className={styles.chipRow}><McpStatusPill tone={priorityTone(item.priority)}>Ưu tiên {priorityLabel(item.priority)}</McpStatusPill><McpStatusPill tone={statusTone(item.status)}>{statusLabel(item.status)}</McpStatusPill></div><div className={styles.title}><span>{item.accountName}</span><h3>{item.title}</h3></div><div className={styles.decision}><span className={[styles.due,late?styles.overdue:""].filter(Boolean).join(" ")}><small>{late?"Quá hạn":"Hạn xử lý"}</small><strong>{item.dueDate||"Chưa đặt hạn"}</strong></span><McpButton variant="secondary" aria-label={`Mở chi tiết việc ${item.title}`} onClick={()=>onOpen(item)}>Xem chi tiết</McpButton></div></McpCard>}
function Detail({item,onClose}:{item:ActionItem|null;onClose:()=>void}){return <McpSheet open={Boolean(item)} onClose={onClose} title={item?item.title:"Chi tiết việc"} description={item?`${item.accountName} · ${item.routeName}`:undefined} footer={<div className={styles.sheetActions}><McpButton variant="secondary" onClick={onClose}>Đóng</McpButton></div>}>{item?<div className={styles.sheet}><div className={styles.focus}><span>Trạng thái</span><strong>{statusLabel(item.status)}</strong><small>{sourceLabel(item.source)} · Ưu tiên {priorityLabel(item.priority)}</small></div><div className={styles.metrics}>{[["Phụ trách",item.owner],["Hạn xử lý",item.dueDate],["Điểm bán",item.accountName],["Tuyến",item.routeName],["Nguồn",sourceLabel(item.source)]].map(([l,v])=><div className={styles.metric} key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><div className={styles.note}><h3>Ghi chú xử lý</h3><p>{item.note}</p></div></div>:null}</McpSheet>}
export function ActionsClientPage({kpis,items}:{kpis:ActionKpi[];items:ActionItem[]}){const[selected,setSelected]=useState<ActionItem|null>(null),cols=useMemo(()=>columns(setSelected),[]),stats=useMemo(()=>({session:items.filter(i=>i.source==="session").length,order:items.filter(i=>i.source==="order").length,field:items.filter(i=>i.source==="field_check").length,manual:items.filter(i=>i.source==="manual").length}),[items]);return <AppShell activeHref="/plans"><div className={styles.page}><McpPageHeader eyebrow="Công việc" title="Kế hoạch & Công việc" description="Theo dõi việc cần làm theo người phụ trách, ưu tiên, hạn xử lý và nguồn phát sinh." actions={<McpStatusPill tone="warning">Cần xử lý</McpStatusPill>}/><FilterBar filters={[{label:"Nguồn",value:"Tất cả"},{label:"Ưu tiên",value:"Tất cả"},{label:"Trạng thái",value:"Cần xử lý"}]}/><section className={styles.kpis}>{kpis.map(i=><KpiCard key={i.label} {...i}/>)}</section><section className={styles.layout}><McpCard className={styles.panel}><div className={styles.head}><h2>Danh sách việc ưu tiên</h2><span>{items.length} việc</span></div><div className={styles.desktop} data-plan-desktop-table="true"><DataTable columns={cols} rows={items} getRowKey={r=>r.id}/></div><div className={styles.mobile} data-plan-mobile-list="true">{items.length?items.map(i=><Mobile item={i} key={i.id} onOpen={setSelected}/>):<p>Chưa có việc cần làm</p>}</div></McpCard><McpCard className={styles.panel}><h2>Phân loại công việc</h2><div className={styles.metrics}>{[["Phiên đi tuyến",stats.session],["Đơn hàng",stats.order],["Ghi nhận / thử sản phẩm",stats.field],["Thủ công",stats.manual]].map(([l,v])=><div className={styles.metric} key={String(l)}><span>{l}</span><strong>{v}</strong></div>)}</div></McpCard></section><Detail item={selected} onClose={()=>setSelected(null)}/></div></AppShell>}
