import { NextRequest, NextResponse } from 'next/server';
import { NPP_SESSION_COOKIE, safeNppReturnTo } from './lib/workforce-session';
const PUBLIC_PATHS=new Set(['/login','/api/auth/login','/api/auth/logout']);
function deny(request:NextRequest,status:401|503,code:string,message:string){const headers=new Headers({'Cache-Control':'no-store'});return request.nextUrl.pathname.startsWith('/api/')?NextResponse.json({error:{code,message,retryable:status===503}},{status,headers}):new NextResponse(message,{status,headers});}
function browser(request:NextRequest){return(request.method==='GET'||request.method==='HEAD')&&Boolean(request.headers.get('accept')?.includes('text/html'));}
function loginRedirect(request:NextRequest){const u=request.nextUrl.clone();u.pathname='/login';u.search='';const r=safeNppReturnTo(`${request.nextUrl.pathname}${request.nextUrl.search}`);if(r!=='/')u.searchParams.set('returnTo',r);return NextResponse.redirect(u);}
function clearInvalidSession(response:NextResponse){response.cookies.set(NPP_SESSION_COOKIE,'',{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/',maxAge:0});return response;}
function e2eBasicAllowed(request:NextRequest){if(process.env.NODE_ENV!=='test')return false;const user=process.env.CORE_WEB_ADMIN_USERNAME?.trim();const pass=process.env.CORE_WEB_ADMIN_PASSWORD||'';if(!user||!pass)return false;const auth=request.headers.get('authorization')||'';if(!auth.startsWith('Basic '))return false;try{return atob(auth.slice(6))===`${user}:${pass}`;}catch{return false;}}
function coreBaseUrl():string|null{const raw=process.env.CORE_API_INTERNAL_URL?.trim();if(!raw)return null;try{const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return null;if(process.env.NODE_ENV==='production'&&u.protocol!=='https:')return null;u.pathname=u.pathname.replace(/\/$/,'');u.search='';u.hash='';return u.toString().replace(/\/$/,'');}catch{return null;}}
async function sessionState(token:string):Promise<'active'|'invalid'|'unavailable'>{const base=coreBaseUrl();if(!base)return'unavailable';const c=new AbortController();const t=setTimeout(()=>c.abort(),3_000);try{const r=await fetch(`${base}/api/internal-auth/me`,{method:'GET',cache:'no-store',signal:c.signal,headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}});if(r.ok)return'active';if(r.status===401||r.status===403)return'invalid';return'unavailable';}catch{return'unavailable';}finally{clearTimeout(t);}}
export async function middleware(request:NextRequest){if(PUBLIC_PATHS.has(request.nextUrl.pathname))return NextResponse.next();if(e2eBasicAllowed(request))return NextResponse.next();const fp=request.headers.get('x-forwarded-proto')?.split(',')[0]?.trim();if(process.env.NODE_ENV==='production'&&fp!=='https'&&request.nextUrl.protocol!=='https:')return deny(request,503,'NPP_HTTPS_REQUIRED','NPP Operations access requires HTTPS');const token=request.cookies.get(NPP_SESSION_COOKIE)?.value?.trim();if(!token)return browser(request)?loginRedirect(request):deny(request,401,'UNAUTHORIZED','Authentication required');const state=await sessionState(token);if(state==='active')return NextResponse.next();if(state==='invalid')return clearInvalidSession(browser(request)?loginRedirect(request):deny(request,401,'UNAUTHORIZED','Authentication required'));return deny(request,503,'NPP_AUTH_UNAVAILABLE','NPP Core authentication is temporarily unavailable');}
export const config={matcher:['/((?!_next/static|_next/image|favicon.ico|manifest.webmanifest|sw.js|offline.html|icons/|logo-transparent.png).*)']};
