import {
  PERMISSIONS as BASE_PERMISSIONS,
  PERMISSION_CATALOG as BASE_PERMISSION_CATALOG,
} from './permissions-sales.js';

export const PERMISSIONS = Object.freeze({
  ...BASE_PERMISSIONS,
  coreInventoryNegativeStockIssue: 'core.inventory.negative-stock.issue',
  coreInventoryTransferReceive: 'core.inventory-transfer.receive',
  coreInventoryTransferDamageApprove: 'core.inventory-transfer.damage-approve',
  coreInventoryTransferResolve: 'core.inventory-transfer.resolve',
  coreStocktakeRead: 'core.stocktake.read',
  coreStocktakeCreate: 'core.stocktake.create',
  coreStocktakeCount: 'core.stocktake.count',
  coreStocktakeSubmit: 'core.stocktake.submit',
  coreStocktakeApprove: 'core.stocktake.approve',
  coreStocktakePost: 'core.stocktake.post',
  coreStocktakeCancel: 'core.stocktake.cancel',
  coreStocktakeReverse: 'core.stocktake.reverse',
  coreInventoryAdjustmentRead: 'core.inventory-adjustment.read',
  coreInventoryAdjustmentCreate: 'core.inventory-adjustment.create',
  coreInventoryAdjustmentSubmit: 'core.inventory-adjustment.submit',
  coreInventoryAdjustmentApprove: 'core.inventory-adjustment.approve',
  coreInventoryAdjustmentPost: 'core.inventory-adjustment.post',
  coreInventoryAdjustmentCancel: 'core.inventory-adjustment.cancel',
  coreInventoryAdjustmentReverse: 'core.inventory-adjustment.reverse',
  coreInventoryManualInboundRead: 'core.inventory-manual-inbound.read',
  coreInventoryManualInboundPrepare: 'core.inventory-manual-inbound.prepare',
  coreInventoryManualInboundPost: 'core.inventory-manual-inbound.post',
  coreInventoryManualInboundReverse: 'core.inventory-manual-inbound.reverse',
  coreInventoryCostRead: 'core.inventory-cost.read',
  coreInventoryCostRebuild: 'core.inventory-cost.rebuild',
  coreInventoryCostReconcile: 'core.inventory-cost.reconcile',
  coreReportingInventoryRead: 'core.reporting.inventory.read',
  coreReportingAgingRead: 'core.reporting.aging.read',
  coreReportingGrossMarginRead: 'core.reporting.gross-margin.read',
  coreReportingEmployeeMcpRead: 'core.reporting.employee-mcp.read',
  coreReportingLogisticsRead: 'core.reporting.logistics.read',
  coreReportingCodRead: 'core.reporting.cod.read',
  coreReportingAuditHistoryRead: 'core.reporting.audit-history.read',
  coreReportingControlTowerRead: 'core.reporting.control-tower.read',
  coreReportingExport: 'core.reporting.export',
  coreManagementProposalSubmit: 'core.management-proposal.submit',
  coreLogisticsRouteRead: 'core.logistics-route.read',
  coreLogisticsRouteManage: 'core.logistics-route.manage',
  coreVehicleRead: 'core.vehicle.read',
  coreVehicleManage: 'core.vehicle.manage',
  coreDriverProfileRead: 'core.driver-profile.read',
  coreDriverProfileManage: 'core.driver-profile.manage',
  coreDeliveryTripRead: 'core.delivery-trip.read',
  coreDeliveryTripCreate: 'core.delivery-trip.create',
  coreDeliveryTripPlan: 'core.delivery-trip.plan',
  coreDeliveryTripAssign: 'core.delivery-trip.assign',
  coreDeliveryTripLock: 'core.delivery-trip.lock',
  coreDeliveryTripDispatch: 'core.delivery-trip.dispatch',
  coreDeliveryTripDriverRead: 'core.delivery-trip.driver-read',
  coreDeliveryAttemptRead: 'core.delivery-attempt.read',
  coreDeliveryAttemptRecord: 'core.delivery-attempt.record',
  corePodRead: 'core.pod.read',
  corePodAttach: 'core.pod.attach',
  coreDeliveryTripReconciliationRead: 'core.delivery-trip.reconciliation-read',
  coreDeliveryTripReturnReceive: 'core.delivery-trip.return-receive',
  coreDeliveryTripClose: 'core.delivery-trip.close',
  coreReceivableRead: 'core.receivable.read',
  coreCustomerPaymentRead: 'core.customer-payment.read',
  coreCustomerPaymentCreate: 'core.customer-payment.create',
  coreCustomerPaymentReverse: 'core.customer-payment.reverse',
  coreReceivableAllocationCreate: 'core.receivable-allocation.create',
  coreReceivableAllocationReverse: 'core.receivable-allocation.reverse',
  coreCustomerReturnCreditRead: 'core.customer-return-credit.read',
  coreCustomerReturnCreditAllocate: 'core.customer-return-credit.allocate',
  coreCustomerReturnCreditReverse: 'core.customer-return-credit.reverse',
  coreCustomerRefundCreate: 'core.customer-refund.create',
  coreCustomerRefundReverse: 'core.customer-refund.reverse',
  coreCodCollectionRead: 'core.cod-collection.read',
  coreCodCollectionRecord: 'core.cod-collection.record',
  coreCodHandoverRead: 'core.cod-handover.read',
  coreCodHandoverCreate: 'core.cod-handover.create',
  coreCodReconciliationRead: 'core.cod-reconciliation.read',
  coreCodReconciliationAccept: 'core.cod-reconciliation.accept',
  coreCodAdjustmentCreate: 'core.cod-adjustment.create',
  coreBackupRead: 'core.backup.read',
  coreBackupCreate: 'core.backup.create',
  coreBackupDownload: 'core.backup.download',
  coreDataDeletionAuthorize: 'core.data-deletion.authorize',
  mcpSessionWrite: 'mcp.session.write',
  mcpSessionCustomerWrite: 'mcp.session-customer.write',
  mcpOrderWrite: 'mcp.order.write',
  mcpTestWrite: 'mcp.test.write',
  mcpReportWrite: 'mcp.report.write',
  mcpFollowupWrite: 'mcp.followup.write',
  mcpSalesOrderRead: 'mcp.sales-order.read',
  mcpSalesOrderCreate: 'mcp.sales-order.create',
  mcpRouteWrite: 'mcp.route.write',
  mcpRouteCustomerWrite: 'mcp.route-customer.write',
  mcpReportSettingWrite: 'mcp.report-setting.write',
});

const NEGATIVE_STOCK_PERMISSION_CATALOG = Object.freeze([
  Object.freeze({
    permissionKey: PERMISSIONS.coreInventoryNegativeStockIssue,
    module: 'Kho',
    label: 'Xuất vượt tồn khả dụng',
    description: 'Cho phép xuất hàng vượt tồn khả dụng tại kho đã bật chính sách tương ứng; hệ thống vẫn kiểm tra phạm vi kho và điều kiện nghiệp vụ.',
    isSystem: true,
  }),
]);

const INVENTORY_TRANSFER_RECEIPT_PERMISSION_CATALOG = Object.freeze([
  ['coreInventoryTransferReceive', 'Kho', 'Nhận hàng chuyển kho', 'Cho phép ghi nhận hàng đạt, hư hỏng và hàng thừa chờ xác minh tại kho đích.'],
  ['coreInventoryTransferDamageApprove', 'Kho', 'Duyệt hư hỏng chuyển kho', 'Cho phép quản lý kho đích xác nhận biên bản hư hỏng của lần nhận chuyển kho.'],
  ['coreInventoryTransferResolve', 'Kho', 'Đóng chênh lệch chuyển kho', 'Cho phép quản lý kho đóng phần thiếu có lý do, không sửa số lượng xuất gốc.'],
].map(([key, module, label, description]) => Object.freeze({ permissionKey: PERMISSIONS[key], module, label, description, isSystem: true })));

const STOCKTAKE_PERMISSION_CATALOG = Object.freeze([
  ['coreStocktakeRead', 'Kho', 'Xem kiểm kê', 'Cho phép đọc danh sách, chi tiết và lịch sử vòng đếm kiểm kê trong phạm vi kho được cấp.'],
  ['coreStocktakeCreate', 'Kho', 'Tạo kiểm kê', 'Cho phép tạo đợt kiểm kê và chụp snapshot tồn theo phạm vi kho được cấp.'],
  ['coreStocktakeCount', 'Kho', 'Ghi nhận số đếm', 'Cho phép nhập số đếm mù và hoàn tất một vòng đếm kiểm kê.'],
  ['coreStocktakeSubmit', 'Kho', 'Gửi duyệt kiểm kê', 'Cho phép khóa vòng đếm hiện tại và gửi kết quả kiểm kê để duyệt.'],
  ['coreStocktakeApprove', 'Kho', 'Duyệt kiểm kê', 'Cho phép yêu cầu đếm lại hoặc duyệt một version kiểm kê do người khác gửi.'],
  ['coreStocktakePost', 'Kho', 'Ghi sổ kiểm kê', 'Cho phép ghi một movement điều chỉnh kiểm kê từ kết quả đã duyệt.'],
  ['coreStocktakeCancel', 'Kho', 'Hủy kiểm kê', 'Cho phép hủy đợt kiểm kê trước khi gửi duyệt.'],
  ['coreStocktakeReverse', 'Kho', 'Đảo ghi sổ kiểm kê', 'Cho phép đảo movement kiểm kê khi chưa có movement phát sinh sau đó trên exact scope.'],
].map(([key, module, label, description]) => Object.freeze({ permissionKey: PERMISSIONS[key], module, label, description, isSystem: true })));

const INVENTORY_ADJUSTMENT_PERMISSION_CATALOG = Object.freeze([
  ['coreInventoryAdjustmentRead', 'Kho', 'Xem phiếu xử lý tồn kho', 'Cho phép đọc phiếu điều chỉnh, cách ly, hư hỏng và tiêu hủy trong phạm vi kho được cấp.'],
  ['coreInventoryAdjustmentCreate', 'Kho', 'Tạo phiếu xử lý tồn kho', 'Cho phép tạo phiếu điều chỉnh, chuyển cách ly, chuyển hư hỏng hoặc tiêu hủy.'],
  ['coreInventoryAdjustmentSubmit', 'Kho', 'Gửi duyệt phiếu xử lý tồn kho', 'Cho phép gửi phiếu xử lý tồn kho để người khác duyệt.'],
  ['coreInventoryAdjustmentApprove', 'Kho', 'Duyệt phiếu xử lý tồn kho', 'Cho phép duyệt phiếu do người khác tạo trong phạm vi kho được cấp.'],
  ['coreInventoryAdjustmentPost', 'Kho', 'Ghi sổ phiếu xử lý tồn kho', 'Cho phép ghi movement append-only sau khi phiếu đã được duyệt.'],
  ['coreInventoryAdjustmentCancel', 'Kho', 'Hủy phiếu xử lý tồn kho', 'Cho phép hủy phiếu trước khi ghi sổ với lý do bắt buộc.'],
  ['coreInventoryAdjustmentReverse', 'Kho', 'Đảo phiếu xử lý tồn kho', 'Cho phép đảo movement khi chưa có movement phát sinh sau đó trên exact scope.'],
].map(([key, module, label, description]) => Object.freeze({ permissionKey: PERMISSIONS[key], module, label, description, isSystem: true })));

const MANUAL_INBOUND_PERMISSION_CATALOG = Object.freeze([
  ['coreInventoryManualInboundRead', 'Kho', 'Xem nhập kho thủ công', 'Cho phép xem chứng từ nhập kho thủ công trong phạm vi kho được cấp.'],
  ['coreInventoryManualInboundPrepare', 'Kho', 'Chuẩn bị nhập kho thủ công', 'Cho phép chuẩn bị và kiểm tra dữ liệu chứng từ nhập kho thủ công trước khi xác nhận.'],
  ['coreInventoryManualInboundPost', 'Kho', 'Xác nhận nhập kho thủ công', 'Cho phép xác nhận chứng từ và ghi hàng vào sổ kho chuẩn.'],
  ['coreInventoryManualInboundReverse', 'Kho', 'Đảo nhập kho thủ công', 'Cho phép đảo chứng từ nhập kho thủ công đã ghi sổ bằng chứng từ đảo có truy vết.'],
].map(([key, module, label, description]) => Object.freeze({ permissionKey: PERMISSIONS[key], module, label, description, isSystem: true })));

const INVENTORY_COST_PERMISSION_CATALOG = Object.freeze([
  ['coreInventoryCostRead', 'Kho', 'Xem giá vốn tồn kho', 'Cho phép đọc số lượng, giá trị, giá bình quân và cost fact trong phạm vi kho được cấp.'],
  ['coreInventoryCostRebuild', 'Kho', 'Dựng lại giá vốn tồn kho', 'Cho phép dựng lại moving-average cost facts và projection từ inventory ledger bất biến.'],
  ['coreInventoryCostReconcile', 'Kho', 'Đối soát giá vốn tồn kho', 'Cho phép đọc đối soát quantity ledger với costing projection và anomaly nguồn giá.'],
].map(([key, module, label, description]) => Object.freeze({ permissionKey: PERMISSIONS[key], module, label, description, isSystem: true })));

const REPORTING_PERMISSION_CATALOG = Object.freeze([
  Object.freeze({ permissionKey: PERMISSIONS.coreReportingInventoryRead, module: 'Báo cáo tồn kho', label: 'Xem báo cáo tồn kho', description: 'Cho phép đọc dashboard tồn kho trong đúng installation và phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreReportingAgingRead, module: 'Báo cáo công nợ', label: 'Xem tuổi nợ phải thu / phải trả', description: 'Cho phép đọc tuổi khoản phải thu và tuổi nợ phải trả trong đúng installation và phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreReportingGrossMarginRead, module: 'Báo cáo lãi gộp', label: 'Xem báo cáo lãi gộp', description: 'Cho phép đọc doanh thu thuần, giá vốn Phase 7 và lãi gộp trong đúng installation và phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreReportingEmployeeMcpRead, module: 'Báo cáo nhân sự & MCP', label: 'Xem hiệu suất nhân viên / MCP', description: 'Cho phép đọc hiệu suất route/session/visit/order-intent của MCP trong đúng installation và phạm vi field có thể xác minh canonical.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreReportingLogisticsRead, module: 'Báo cáo giao hàng', label: 'Xem hiệu suất giao hàng / logistics', description: 'Cho phép đọc báo cáo chuyến, điểm dừng, kết quả giao và hiệu suất tài xế/phương tiện trong đúng installation và phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreReportingCodRead, module: 'Báo cáo COD', label: 'Xem COD & đối soát vận hành', description: 'Cho phép đọc trạng thái thu COD, tiền tài xế đang giữ, bàn giao, kế toán tiếp nhận và ngoại lệ trong đúng installation và phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreReportingAuditHistoryRead, module: 'Lịch sử vận hành', label: 'Xem audit và lịch sử import/export', description: 'Cho phép đọc audit/activity append-only và metadata lịch sử import/export canonical trong đúng installation.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreReportingControlTowerRead, module: 'Điều hành quản lý', label: 'Xem Admin Control Tower', description: 'Cho phép đọc tập aggregate quản lý đã phê duyệt từ các contract báo cáo Phase 8 trong phạm vi được cấp; không cấp quyền xem toàn bộ chi tiết.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreReportingExport, module: 'Xuất báo cáo', label: 'Yêu cầu xuất báo cáo chính thức', description: 'Cho phép yêu cầu export canonical khi đồng thời có quyền đọc report-family tương ứng; quyền này không tự cấp quyền xem báo cáo.', isSystem: true }),
]);

const MANAGEMENT_PERMISSION_CATALOG = Object.freeze([
  Object.freeze({ permissionKey: PERMISSIONS.coreManagementProposalSubmit, module: 'Đề xuất quản trị', label: 'Gửi đề xuất quản trị', description: 'Cho phép nhân viên Công Ty gửi đề xuất lên Admin và đọc lại đúng đề xuất do mình tạo.', isSystem: true }),
]);

const MCP_PERMISSION_CATALOG = Object.freeze([
  ['mcpSessionWrite', 'MCP hiện trường', 'Thực hiện phiên đi tuyến', 'Cho phép mở và cập nhật phiên đi tuyến theo phạm vi được giao.'],
  ['mcpSessionCustomerWrite', 'MCP hiện trường', 'Cập nhật điểm bán trong phiên', 'Cho phép cập nhật trạng thái điểm bán thuộc phiên đi tuyến đang phụ trách.'],
  ['mcpOrderWrite', 'MCP hiện trường', 'Ghi nhận đơn tại điểm bán', 'Cho phép ghi nhận nghiệp vụ đơn hàng tại điểm bán trong phiên MCP.'],
  ['mcpTestWrite', 'MCP hiện trường', 'Ghi nhận kiểm tra tại điểm bán', 'Cho phép ghi nhận kết quả kiểm tra nghiệp vụ tại điểm bán.'],
  ['mcpReportWrite', 'MCP hiện trường', 'Ghi báo cáo thị trường', 'Cho phép lập và cập nhật báo cáo thị trường trong phiên được giao.'],
  ['mcpFollowupWrite', 'MCP hiện trường', 'Ghi việc cần theo dõi', 'Cho phép tạo và cập nhật việc cần theo dõi phát sinh từ hoạt động thị trường.'],
  ['mcpSalesOrderRead', 'MCP bán hàng', 'Xem đơn Công Ty từ MCP', 'Cho phép MCP đọc đơn Công Ty theo phạm vi kho được cấp.'],
  ['mcpSalesOrderCreate', 'MCP bán hàng', 'Tạo đơn Công Ty từ MCP', 'Cho phép MCP tạo đơn Công Ty cho khách đã mở mã theo phạm vi được cấp.'],
  ['mcpRouteWrite', 'Cấu hình MCP', 'Quản lý tuyến cố định', 'Cho phép tạo, sửa và ngừng sử dụng tuyến bán hàng cố định.'],
  ['mcpRouteCustomerWrite', 'Cấu hình MCP', 'Quản lý điểm bán trong tuyến', 'Cho phép thêm, sửa và loại điểm bán khỏi danh sách tuyến cố định.'],
  ['mcpReportSettingWrite', 'Cấu hình MCP', 'Quản lý mẫu báo cáo thị trường', 'Cho phép thay đổi các lựa chọn dùng chung trong cấu hình báo cáo thị trường.'],
].map(([key, module, label, description]) => Object.freeze({ permissionKey: PERMISSIONS[key], module, label, description, isSystem: true })));

const LOGISTICS_PERMISSION_CATALOG = Object.freeze([
  ['coreLogisticsRouteRead', 'Điều phối giao hàng', 'Xem tuyến giao hàng', 'Cho phép đọc tuyến giao hàng trong installation hiện tại.'],
  ['coreLogisticsRouteManage', 'Điều phối giao hàng', 'Quản lý tuyến giao hàng', 'Cho phép tạo tuyến giao hàng phục vụ lập kế hoạch chuyến.'],
  ['coreVehicleRead', 'Điều phối giao hàng', 'Xem phương tiện', 'Cho phép đọc danh mục phương tiện giao hàng.'],
  ['coreVehicleManage', 'Điều phối giao hàng', 'Quản lý phương tiện', 'Cho phép tạo phương tiện giao hàng phục vụ điều phối.'],
  ['coreDriverProfileRead', 'Điều phối giao hàng', 'Xem tài xế', 'Cho phép đọc hồ sơ tài xế giao hàng.'],
  ['coreDriverProfileManage', 'Điều phối giao hàng', 'Quản lý tài xế', 'Cho phép tạo hồ sơ tài xế giao hàng.'],
  ['coreDeliveryTripRead', 'Điều phối giao hàng', 'Xem chuyến giao', 'Cho phép đọc chuyến, điểm dừng và phiếu giao được gán trong phạm vi kho.'],
  ['coreDeliveryTripCreate', 'Điều phối giao hàng', 'Tạo chuyến giao', 'Cho phép tạo chuyến giao nháp trong phạm vi kho.'],
  ['coreDeliveryTripPlan', 'Điều phối giao hàng', 'Lập kế hoạch chuyến', 'Cho phép cập nhật xe, tài xế, thời gian và trạng thái planned của chuyến.'],
  ['coreDeliveryTripAssign', 'Điều phối giao hàng', 'Gán phiếu giao vào chuyến', 'Cho phép gán, bỏ gán và xếp thứ tự điểm dừng trước khi khóa.'],
  ['coreDeliveryTripLock', 'Điều phối giao hàng', 'Khóa kế hoạch chuyến', 'Cho phép khóa kế hoạch chuyến đã đủ xe, tài xế và phiếu giao.'],
  ['coreDeliveryTripDispatch', 'Điều phối giao hàng', 'Bàn giao và cho chuyến xuất phát', 'Cho phép xác nhận bàn giao vật lý, ghi Inventory OUT cho toàn bộ Delivery Order và chuyển chuyến đã khóa sang dispatched.'],
  ['coreDeliveryTripDriverRead', 'Giao hàng', 'Xem chuyến được giao', 'Cho phép tài xế đọc các chuyến đã xuất phát được gán đúng cho hồ sơ tài xế liên kết với nhân viên của mình.'],
  ['coreDeliveryAttemptRead', 'Giao hàng', 'Xem kết quả lần giao', 'Cho phép đọc kết quả lần giao trong phạm vi chuyến và kho được cấp quyền.'],
  ['coreDeliveryAttemptRecord', 'Giao hàng', 'Ghi kết quả lần giao', 'Cho phép tài xế được xác thực ghi đúng một kết quả terminal cho assignment thuộc chuyến của mình.'],
  ['corePodRead', 'Giao hàng', 'Xem bằng chứng giao hàng', 'Cho phép đọc POD gắn với delivery attempt trong phạm vi tài xế hoặc kho được cấp quyền.'],
  ['corePodAttach', 'Giao hàng', 'Đính kèm bằng chứng giao hàng', 'Cho phép tài xế đã xác thực đính kèm POD tùy chọn vào delivery attempt thuộc chuyến của mình.'],
  ['coreDeliveryTripReconciliationRead', 'Đối soát giao hàng', 'Xem đối soát cuối chuyến', 'Cho phép đọc số đã xuất, đã giao, đã nhận lại và còn trên xe trong phạm vi kho.'],
  ['coreDeliveryTripReturnReceive', 'Đối soát giao hàng', 'Nhận hàng chưa giao về kho', 'Cho phép kho xác nhận thực nhận hàng chưa giao và ghi Inventory IN theo exact issue-line lineage.'],
  ['coreDeliveryTripClose', 'Đối soát giao hàng', 'Đóng chuyến đã đối soát', 'Cho phép đóng chuyến khi mọi phiếu có kết quả và toàn bộ hàng đã giao hoặc đã nhận lại kho.'],
  ['coreCodCollectionRead', 'COD giao hàng', 'Xem tiền COD theo chuyến', 'Cho phép đọc tiền COD và số tiền tài xế đang giữ trong đúng phạm vi chuyến/kho.'],
  ['coreCodCollectionRecord', 'COD giao hàng', 'Ghi nhận tiền COD đã thu', 'Cho phép tài xế ghi tiền thực thu hoặc lời hẹn của đúng phiếu giao được giao.'],
  ['coreCodHandoverRead', 'COD giao hàng', 'Xem bàn giao tiền COD', 'Cho phép đọc các lần bàn giao tiền COD trong phạm vi được cấp.'],
  ['coreCodHandoverCreate', 'COD giao hàng', 'Lập bàn giao tiền COD', 'Cho phép tài xế lập bàn giao tiền mặt COD theo exact collection lineage.'],
].map(([key, module, label, description]) => Object.freeze({ permissionKey: PERMISSIONS[key], module, label, description, isSystem: true })));

const ACCOUNTING_PERMISSION_CATALOG = Object.freeze([
  ['coreReceivableRead', 'Công nợ khách hàng', 'Xem công nợ khách hàng', 'Cho phép đọc số dư, chứng từ và sổ chi tiết công nợ khách hàng trong phạm vi kho được cấp.'],
  ['coreCustomerPaymentRead', 'Thu tiền khách hàng', 'Xem phiếu thu khách hàng', 'Cho phép đọc phiếu thu và lịch sử ghi tiền vào đơn trong phạm vi kho được cấp.'],
  ['coreCustomerPaymentCreate', 'Thu tiền khách hàng', 'Ghi nhận tiền khách trả', 'Cho phép ghi nhận tiền mặt hoặc chuyển khoản đã thực nhận từ khách hàng.'],
  ['coreCustomerPaymentReverse', 'Thu tiền khách hàng', 'Hủy phiếu thu khách hàng', 'Cho phép hủy phiếu thu không còn khoản nào đang ghi vào đơn, với lý do bắt buộc.'],
  ['coreReceivableAllocationCreate', 'Công nợ khách hàng', 'Ghi tiền thu vào công nợ', 'Cho phép ghi một phiếu thu vào một hoặc nhiều khoản phải thu trong phạm vi được cấp.'],
  ['coreReceivableAllocationReverse', 'Công nợ khách hàng', 'Hủy phần tiền đã ghi', 'Cho phép hủy phần tiền đã ghi và lưu đầy đủ lịch sử điều chỉnh.'],
  ['coreCustomerReturnCreditRead', 'Điều chỉnh công nợ khách hàng', 'Xem credit hàng khách trả', 'Cho phép đọc credit phát sinh từ Customer Return đã được kho nhận trong phạm vi kho.'],
  ['coreCustomerReturnCreditAllocate', 'Điều chỉnh công nợ khách hàng', 'Phân bổ credit hàng khách trả', 'Cho phép phân bổ phần credit chưa dùng vào khoản phải thu hợp lệ.'],
  ['coreCustomerReturnCreditReverse', 'Điều chỉnh công nợ khách hàng', 'Đảo credit hàng khách trả', 'Cho phép đảo credit bằng bút toán bù sau khi hoàn tiền liên quan đã được đảo.'],
  ['coreCustomerRefundCreate', 'Hoàn tiền khách hàng', 'Hoàn tiền từ số dư credit', 'Cho phép ghi nhận hoàn tiền từ credit chưa phân bổ, với nơi nhận và lý do bắt buộc.'],
  ['coreCustomerRefundReverse', 'Hoàn tiền khách hàng', 'Đảo hoàn tiền khách hàng', 'Cho phép đảo một khoản hoàn tiền bằng bút toán bù bất biến.'],
  ['coreCodReconciliationRead', 'Đối soát COD', 'Xem đối soát tiền COD', 'Cho phép kế toán/thu ngân đọc collection, bàn giao, tiền thực nhận và chênh lệch COD.'],
  ['coreCodReconciliationAccept', 'Đối soát COD', 'Xác nhận tiền COD công ty nhận', 'Cho phép kế toán/thu ngân xác nhận số tiền thực nhận và trạng thái đối soát COD.'],
  ['coreCodAdjustmentCreate', 'Đối soát COD', 'Đảo hoặc điều chỉnh COD', 'Cho phép tạo reversal/adjustment append-only cho collection, bàn giao hoặc xác nhận COD.'],
].map(([key, module, label, description]) => Object.freeze({ permissionKey: PERMISSIONS[key], module, label, description, isSystem: true })));

const BACKUP_PERMISSION_CATALOG = Object.freeze([
  ['coreBackupRead', 'Dữ liệu & sao lưu', 'Xem bản sao lưu', 'Cho phép xem trạng thái và lịch sử bản sao lưu của installation hiện tại.'],
  ['coreBackupCreate', 'Dữ liệu & sao lưu', 'Tạo bản sao lưu', 'Cho phép yêu cầu sao lưu toàn bộ dữ liệu canonical của installation hiện tại.'],
  ['coreBackupDownload', 'Dữ liệu & sao lưu', 'Tải bản sao lưu', 'Cho phép cấp liên kết tải ngắn hạn cho artifact sao lưu đã xác minh.'],
  ['coreDataDeletionAuthorize', 'Dữ liệu & sao lưu', 'Xác minh yêu cầu xóa dữ liệu', 'Cho phép tạo và xác minh Delete Intent đã được bảo vệ bằng backup VERIFIED và mã Owner.'],
].map(([key, module, label, description]) => Object.freeze({ permissionKey: PERMISSIONS[key], module, label, description, isSystem: true })));

export const PERMISSION_CATALOG = Object.freeze([
  ...BASE_PERMISSION_CATALOG,
  ...NEGATIVE_STOCK_PERMISSION_CATALOG,
  ...INVENTORY_TRANSFER_RECEIPT_PERMISSION_CATALOG,
  ...STOCKTAKE_PERMISSION_CATALOG,
  ...INVENTORY_ADJUSTMENT_PERMISSION_CATALOG,
  ...MANUAL_INBOUND_PERMISSION_CATALOG,
  ...INVENTORY_COST_PERMISSION_CATALOG,
  ...REPORTING_PERMISSION_CATALOG,
  ...MANAGEMENT_PERMISSION_CATALOG,
  ...MCP_PERMISSION_CATALOG,
  ...LOGISTICS_PERMISSION_CATALOG,
  ...ACCOUNTING_PERMISSION_CATALOG,
  ...BACKUP_PERMISSION_CATALOG,
]);
export const PERMISSION_REGISTRY = new Set(PERMISSION_CATALOG.map((entry) => entry.permissionKey));
export function isKnownPermissionKey(value) { return typeof value === 'string' && PERMISSION_REGISTRY.has(value); }
export function createPermissionCatalogRows(occurredAt = new Date().toISOString()) { return PERMISSION_CATALOG.map((entry) => ({ permission_key: entry.permissionKey, module: entry.module, label: entry.label, description: entry.description, is_system: entry.isSystem, created_at: occurredAt })); }
