export const PERMISSIONS = Object.freeze({
  coreConfigRead: 'core.config.read',
  coreHealthAuthenticatedRead: 'core.health.authenticated.read',
  coreIdempotencyTestWrite: 'core.idempotency.test.write',
  coreAuditOutboxTestWrite: 'core.audit-outbox.test.write',
  coreStorageR2TestWrite: 'core.storage.r2.test.write',
  coreOrganizationRead: 'core.organization.read',
  coreOrganizationWrite: 'core.organization.write',
  coreBranchRead: 'core.branch.read',
  coreBranchWrite: 'core.branch.write',
  coreWarehouseRead: 'core.warehouse.read',
  coreWarehouseWrite: 'core.warehouse.write',
  coreWarehouseLocationRead: 'core.warehouse.location.read',
  coreWarehouseLocationWrite: 'core.warehouse.location.write',
  coreCustomerRead: 'core.customer.read',
  coreCustomerWrite: 'core.customer.write',
  coreSupplierRead: 'core.supplier.read',
  coreSupplierWrite: 'core.supplier.write',
  coreProductRead: 'core.product.read',
  coreProductWrite: 'core.product.write',
  corePriceRead: 'core.price.read',
  corePriceWrite: 'core.price.write',
  coreDocumentNumberRead: 'core.document-number.read',
  coreDocumentNumberWrite: 'core.document-number.write',
  corePrintTemplateRead: 'core.print-template.read',
  corePrintTemplateManage: 'core.print-template.manage',
  coreInventoryRead: 'core.inventory.read',
  coreInventoryPost: 'core.inventory.post',
  coreInventoryReverse: 'core.inventory.reverse',
  coreInventoryReserve: 'core.inventory.reserve',
  coreInventoryTrackingPolicyRead: 'core.inventory.tracking-policy.read',
  coreInventoryTrackingPolicyManage: 'core.inventory.tracking-policy.manage',
  coreInventoryLotRead: 'core.inventory.lot.read',
  coreInventoryLotManage: 'core.inventory.lot.manage',
  coreInventoryOpeningBalanceImport: 'core.inventory.opening-balance.import',
  coreInventoryTransferRead: 'core.inventory-transfer.read',
  coreInventoryTransferCreate: 'core.inventory-transfer.create',
  coreInventoryTransferUpdate: 'core.inventory-transfer.update',
  coreInventoryTransferApprove: 'core.inventory-transfer.approve',
  coreInventoryTransferDispatch: 'core.inventory-transfer.dispatch',
  coreInventoryTransferCancel: 'core.inventory-transfer.cancel',
  coreInventoryTransferReverse: 'core.inventory-transfer.reverse',
  corePurchaseOrderRead: 'core.purchase-order.read',
  corePurchaseOrderCreate: 'core.purchase-order.create',
  corePurchaseOrderUpdate: 'core.purchase-order.update',
  corePurchaseOrderSubmit: 'core.purchase-order.submit',
  corePurchaseOrderApprove: 'core.purchase-order.approve',
  corePurchaseOrderCancel: 'core.purchase-order.cancel',
  coreGoodsReceiptRead: 'core.goods-receipt.read',
  coreGoodsReceiptCreate: 'core.goods-receipt.create',
  coreGoodsReceiptUpdate: 'core.goods-receipt.update',
  coreGoodsReceiptPost: 'core.goods-receipt.post',
  coreGoodsReceiptReverse: 'core.goods-receipt.reverse',
  coreGoodsReceiptVariance: 'core.goods-receipt.variance',
  coreSupplierReturnRead: 'core.supplier-return.read',
  coreSupplierReturnCreate: 'core.supplier-return.create',
  coreSupplierReturnUpdate: 'core.supplier-return.update',
  coreSupplierReturnSubmit: 'core.supplier-return.submit',
  coreSupplierReturnApprove: 'core.supplier-return.approve',
  coreSupplierReturnCancel: 'core.supplier-return.cancel',
  coreSupplierReturnPost: 'core.supplier-return.post',
  coreSupplierReturnReverse: 'core.supplier-return.reverse',
  coreEmployeeRead: 'core.employee.read',
  coreEmployeeWrite: 'core.employee.write',
  coreUserRead: 'core.user.read',
  coreUserWrite: 'core.user.write',
  coreUserRoleWrite: 'core.user-role.write',
  corePermissionRead: 'core.permission.read',
  coreRoleRead: 'core.role.read',
  coreRoleWrite: 'core.role.write',
});

export const PERMISSION_CATALOG = Object.freeze([
  Object.freeze({ permissionKey: PERMISSIONS.coreConfigRead, module: 'Hệ thống', label: 'Xem cấu hình hệ thống', description: 'Cho phép đọc thông tin cấu hình và trạng thái nền tảng đã được chuẩn hóa.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreHealthAuthenticatedRead, module: 'Hệ thống', label: 'Xem trạng thái xác thực', description: 'Cho phép đọc trạng thái sức khỏe có xác thực của Core API.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreIdempotencyTestWrite, module: 'Hệ thống', label: 'Kiểm thử idempotency', description: 'Cho phép thực thi luồng kiểm thử idempotency ở tầng Core.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreAuditOutboxTestWrite, module: 'Hệ thống', label: 'Kiểm thử audit/outbox', description: 'Cho phép thực thi kiểm thử giao dịch audit và outbox của Core API.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreStorageR2TestWrite, module: 'Hệ thống', label: 'Kiểm thử lưu trữ R2', description: 'Cho phép thực thi kiểm thử tích hợp lưu trữ đối tượng của Core.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreOrganizationRead, module: 'Tổ chức', label: 'Xem cấu trúc tổ chức', description: 'Cho phép đọc tổng quan cơ cấu tổ chức và các đơn vị trực thuộc.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreOrganizationWrite, module: 'Tổ chức', label: 'Quản lý cấu trúc tổ chức', description: 'Cho phép chỉnh sửa thông tin tổng quan cơ cấu tổ chức.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreBranchRead, module: 'Tổ chức', label: 'Xem chi nhánh', description: 'Cho phép đọc danh sách và chi tiết chi nhánh.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreBranchWrite, module: 'Tổ chức', label: 'Quản lý chi nhánh', description: 'Cho phép tạo, cập nhật và thay đổi trạng thái chi nhánh.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreWarehouseRead, module: 'Tổ chức', label: 'Xem kho hàng', description: 'Cho phép đọc danh sách và chi tiết kho hàng.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreWarehouseWrite, module: 'Tổ chức', label: 'Quản lý kho hàng', description: 'Cho phép tạo, cập nhật và thay đổi trạng thái kho hàng.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreWarehouseLocationRead, module: 'Tổ chức', label: 'Xem vị trí kho', description: 'Cho phép đọc danh sách và chi tiết vị trí kho hàng.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreWarehouseLocationWrite, module: 'Tổ chức', label: 'Quản lý vị trí kho', description: 'Cho phép tạo, cập nhật và thay đổi trạng thái vị trí kho.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreCustomerRead, module: 'Tổ chức', label: 'Xem khách hàng', description: 'Cho phép đọc danh sách và chi tiết khách hàng.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreCustomerWrite, module: 'Tổ chức', label: 'Quản lý khách hàng', description: 'Cho phép tạo, cập nhật và thay đổi trạng thái khách hàng.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierRead, module: 'Tổ chức', label: 'Xem nhà cung cấp', description: 'Cho phép đọc danh sách và chi tiết nhà cung cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierWrite, module: 'Tổ chức', label: 'Quản lý nhà cung cấp', description: 'Cho phép tạo, cập nhật và thay đổi trạng thái nhà cung cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreProductRead, module: 'Sản phẩm', label: 'Xem danh mục sản phẩm', description: 'Cho phép đọc danh mục, thương hiệu, sản phẩm và SKU.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreProductWrite, module: 'Sản phẩm', label: 'Quản lý danh mục sản phẩm', description: 'Cho phép tạo, cập nhật, nhập và thay đổi trạng thái danh mục sản phẩm.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePriceRead, module: 'Giá bán', label: 'Xem bảng giá', description: 'Cho phép đọc kênh bán, bảng giá, quy tắc giá và kết quả phân giải giá.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePriceWrite, module: 'Giá bán', label: 'Quản lý bảng giá', description: 'Cho phép tạo, cập nhật, nhập và thay đổi trạng thái bảng giá, quy tắc giá và chương trình.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreDocumentNumberRead, module: 'Số chứng từ', label: 'Xem cấu hình số chứng từ', description: 'Cho phép đọc series, bộ đếm và lịch sử cấp số chứng từ.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreDocumentNumberWrite, module: 'Số chứng từ', label: 'Quản lý và cấp số chứng từ', description: 'Cho phép tạo, cập nhật series và cấp số chứng từ theo hợp đồng idempotent.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePrintTemplateRead, module: 'Mẫu in', label: 'Xem cấu hình mẫu in', description: 'Cho phép đọc các mẫu in và phần thông tin được phép hiển thị trên chứng từ.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePrintTemplateManage, module: 'Mẫu in', label: 'Quản lý cấu hình mẫu in', description: 'Cho phép thay đổi khổ giấy và các phần được in của mẫu chứng từ dùng chung.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryRead, module: 'Kho', label: 'Xem sổ kho', description: 'Cho phép đọc movement và drill-down sổ kho trong phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryPost, module: 'Kho', label: 'Ghi sổ kho', description: 'Cho phép domain nội bộ ghi movement kho theo hợp đồng idempotent và phạm vi kho.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryReverse, module: 'Kho', label: 'Đảo movement kho', description: 'Cho phép tạo movement đảo cho movement đã post trong phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryReserve, module: 'Kho', label: 'Cấp phát kho', description: 'Cho phép tạo, phát hành, tiêu thụ và hủy cấp phát kho theo đơn vị khối trong phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryTrackingPolicyRead, module: 'Kho', label: 'Xem chính sách lô và hạn', description: 'Cho phép đọc chính sách theo dõi lô, hạn dùng và yêu cầu vị trí cho SKU inventory-base.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryTrackingPolicyManage, module: 'Kho', label: 'Quản lý chính sách lô và hạn', description: 'Cho phép tạo, cập nhật và khóa chính sách theo dõi lô, hạn dùng và vị trí.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryLotRead, module: 'Kho', label: 'Xem danh mục lô', description: 'Cho phép đọc danh mục lô canonical và tra cứu quan hệ lô của tồn kho.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryLotManage, module: 'Kho', label: 'Quản lý danh mục lô', description: 'Cho phép khởi tạo lô canonical phục vụ posting và opening balance.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryOpeningBalanceImport, module: 'Kho', label: 'Nhập số dư đầu kỳ', description: 'Cho phép xác thực và post opening balance qua hợp đồng import idempotent.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryTransferRead, module: 'Kho', label: 'Xem phiếu chuyển kho', description: 'Cho phép đọc phiếu chuyển kho và hàng đang đi đường trong phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryTransferCreate, module: 'Kho', label: 'Tạo phiếu chuyển kho', description: 'Cho phép tạo phiếu chuyển kho nháp giữa hai kho được cấp quyền.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryTransferUpdate, module: 'Kho', label: 'Sửa phiếu chuyển kho', description: 'Cho phép cập nhật phiếu chuyển kho khi còn ở trạng thái nháp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryTransferApprove, module: 'Kho', label: 'Duyệt phiếu chuyển kho', description: 'Cho phép duyệt phiếu chuyển kho trước khi xuất kho nguồn.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryTransferDispatch, module: 'Kho', label: 'Xuất chuyển kho', description: 'Cho phép ghi sổ xuất kho nguồn và đưa hàng vào trạng thái đang đi đường.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryTransferCancel, module: 'Kho', label: 'Hủy phiếu chuyển kho', description: 'Cho phép hủy phiếu chuyển kho trước khi xuất kho nguồn.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreInventoryTransferReverse, module: 'Kho', label: 'Đảo xuất chuyển kho', description: 'Dành cho slice xử lý đảo/chứng từ bù sau khi chính sách nhận chuyển kho được khóa.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePurchaseOrderRead, module: 'Mua hàng', label: 'Xem đơn đặt hàng', description: 'Cho phép đọc danh sách và chi tiết đơn đặt hàng trong phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePurchaseOrderCreate, module: 'Mua hàng', label: 'Tạo đơn đặt hàng', description: 'Cho phép tạo đơn đặt hàng ở trạng thái nháp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePurchaseOrderUpdate, module: 'Mua hàng', label: 'Sửa đơn đặt hàng', description: 'Cho phép cập nhật đơn đặt hàng khi còn ở trạng thái nháp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePurchaseOrderSubmit, module: 'Mua hàng', label: 'Gửi duyệt đơn đặt hàng', description: 'Cho phép gửi đơn đặt hàng nháp sang trạng thái chờ duyệt.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePurchaseOrderApprove, module: 'Mua hàng', label: 'Duyệt đơn đặt hàng', description: 'Cho phép duyệt đơn đặt hàng, cấp số chứng từ và khóa nội dung.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePurchaseOrderCancel, module: 'Mua hàng', label: 'Hủy đơn đặt hàng', description: 'Cho phép hủy đơn đặt hàng theo chính sách trạng thái.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreGoodsReceiptRead, module: 'Mua hàng', label: 'Xem phiếu nhận hàng', description: 'Cho phép đọc danh sách và chi tiết phiếu nhận hàng trong phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreGoodsReceiptCreate, module: 'Mua hàng', label: 'Tạo phiếu nhận hàng', description: 'Cho phép tạo phiếu nhận hàng nháp cho một PO đã được duyệt.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreGoodsReceiptUpdate, module: 'Mua hàng', label: 'Sửa phiếu nhận hàng', description: 'Cho phép cập nhật phiếu nhận hàng khi còn ở trạng thái nháp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreGoodsReceiptPost, module: 'Mua hàng', label: 'Ghi sổ phiếu nhận hàng', description: 'Cho phép post phiếu nhận hàng và phát sinh inventory movement theo hợp đồng nội bộ.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreGoodsReceiptReverse, module: 'Mua hàng', label: 'Đảo phiếu nhận hàng', description: 'Cho phép phát hành chứng từ bù để đảo phiếu nhận hàng đã post.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreGoodsReceiptVariance, module: 'Mua hàng', label: 'Xử lý chênh lệch phiếu nhận', description: 'Cho phép nhập, ghi sổ và chốt chênh lệch chất lượng/số lượng trên phiếu nhận hàng.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierReturnRead, module: 'Mua hàng', label: 'Xem phiếu trả nhà cung cấp', description: 'Cho phép đọc danh sách, chi tiết và lịch sử phiếu trả nhà cung cấp trong phạm vi kho được cấp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierReturnCreate, module: 'Mua hàng', label: 'Tạo phiếu trả nhà cung cấp', description: 'Cho phép tạo phiếu trả nhà cung cấp nháp từ các dòng phiếu nhận hàng đã ghi sổ.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierReturnUpdate, module: 'Mua hàng', label: 'Sửa phiếu trả nhà cung cấp', description: 'Cho phép cập nhật phiếu trả nhà cung cấp khi còn ở trạng thái nháp.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierReturnSubmit, module: 'Mua hàng', label: 'Gửi duyệt phiếu trả nhà cung cấp', description: 'Cho phép chuyển phiếu trả nhà cung cấp từ nháp sang chờ duyệt.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierReturnApprove, module: 'Mua hàng', label: 'Duyệt phiếu trả nhà cung cấp', description: 'Cho phép duyệt phiếu trả nhà cung cấp trước khi ghi sổ.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierReturnCancel, module: 'Mua hàng', label: 'Hủy phiếu trả nhà cung cấp', description: 'Cho phép hủy phiếu trả nhà cung cấp trước khi ghi sổ với lý do bắt buộc.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierReturnPost, module: 'Mua hàng', label: 'Ghi sổ phiếu trả nhà cung cấp', description: 'Cho phép ghi sổ phiếu trả nhà cung cấp và phát sinh inventory movement xuất kho.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreSupplierReturnReverse, module: 'Mua hàng', label: 'Đảo phiếu trả nhà cung cấp', description: 'Cho phép phát hành chứng từ bù để đảo phiếu trả nhà cung cấp đã ghi sổ.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreEmployeeRead, module: 'Nhân sự', label: 'Xem nhân sự', description: 'Cho phép đọc hồ sơ nhân sự nghiệp vụ.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreEmployeeWrite, module: 'Nhân sự', label: 'Quản lý nhân sự', description: 'Cho phép tạo, cập nhật và thay đổi trạng thái hồ sơ nhân sự.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreUserRead, module: 'Nhân sự', label: 'Xem người dùng', description: 'Cho phép đọc thông tin định danh người dùng và liên kết vai trò/nhân viên.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreUserWrite, module: 'Nhân sự', label: 'Quản lý người dùng', description: 'Cho phép tạo, cập nhật và quản lý liên kết vai trò/nhân viên của người dùng.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreUserRoleWrite, module: 'Nhân sự', label: 'Quản lý liên kết vai trò người dùng', description: 'Cho phép thay thế toàn bộ tập vai trò của người dùng một cách nguyên tử.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.corePermissionRead, module: 'Phân quyền', label: 'Xem danh mục quyền', description: 'Cho phép đọc danh mục quyền chuẩn hóa của Core Platform.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreRoleRead, module: 'Phân quyền', label: 'Xem vai trò', description: 'Cho phép đọc danh sách và chi tiết vai trò quản trị.', isSystem: true }),
  Object.freeze({ permissionKey: PERMISSIONS.coreRoleWrite, module: 'Phân quyền', label: 'Quản lý vai trò', description: 'Cho phép tạo, cập nhật, bật/tắt và thay thế tập quyền của vai trò.', isSystem: true }),
]);

export const PERMISSION_REGISTRY = new Set(PERMISSION_CATALOG.map((entry) => entry.permissionKey));

export function isKnownPermissionKey(value) {
  return typeof value === 'string' && PERMISSION_REGISTRY.has(value);
}

export function createPermissionCatalogRows(occurredAt = new Date().toISOString()) {
  return PERMISSION_CATALOG.map((entry) => ({
    permission_key: entry.permissionKey,
    module: entry.module,
    label: entry.label,
    description: entry.description,
    is_system: entry.isSystem,
    created_at: occurredAt,
  }));
}
