'use client';

import { formatExactDecimal } from '../../../lib/decimal-display.js';
import BusinessDocumentPrint from '../../components/business-document-print';
type ReconciliationLine = Readonly<{ assignmentId: string; stopSequence: number; deliveryOrderNumber: string | null; customerCode: string | null; customerName: string | null; attemptResult: 'delivered_full' | 'delivered_partial' | 'failed' | 'rescheduled' | null; sku: string; itemName: string; unitCode: string; lotCode: string | null; issuedBaseQuantity: string; deliveredBaseQuantity: string; returnedBaseQuantity: string; outstandingBaseQuantity: string }>;
type Reconciliation = Readonly<{ id: string; number: string; status: string; warehouseCode: string | null; warehouseName: string | null; licensePlate: string | null; driverName: string | null; canClose: boolean; closedAt: string | null; lines: readonly ReconciliationLine[]; receipts: readonly { id: string; receivedAt: string }[] }>;
const RESULT_LABELS: Record<NonNullable<ReconciliationLine['attemptResult']>, string> = { delivered_full: 'Giao đủ', delivered_partial: 'Giao một phần', failed: 'Không giao được', rescheduled: 'Hẹn giao lại' };
function dateTime(value: string | null) { if (!value) return '—'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleString('vi-VN'); }
export default function TripReconciliationPrintDock({ reconciliation }: { reconciliation: Reconciliation | null }) {
  if (!reconciliation) return null;
  return <BusinessDocumentPrint id={`trip-reconciliation-${reconciliation.id}`} actionLabel="In" title="BIÊN BẢN ĐỐI SOÁT CHUYẾN" subtitle="Đối chiếu giao hàng và hàng quay về" number={reconciliation.number} status={reconciliation.status === 'closed' ? 'Đã đóng chuyến' : 'Đang đối soát'}
    meta={[{ label: 'Kho', value: `${reconciliation.warehouseCode || '—'} — ${reconciliation.warehouseName || '—'}` }, { label: 'Xe', value: reconciliation.licensePlate || '—' }, { label: 'Tài xế', value: reconciliation.driverName || '—' }, { label: 'Số lần nhập hàng về', value: reconciliation.receipts.length }, { label: 'Thời điểm đóng', value: dateTime(reconciliation.closedAt) }, { label: 'Có thể đóng', value: reconciliation.canClose ? 'Có' : 'Chưa' }]}
    columns={[{ key: 'stop', label: 'Điểm', align: 'center' }, { key: 'order', label: 'Phiếu giao' }, { key: 'customer', label: 'Khách hàng' }, { key: 'item', label: 'SKU / hàng hóa' }, { key: 'result', label: 'Kết quả' }, { key: 'issued', label: 'Xuất', align: 'right' }, { key: 'delivered', label: 'Đã giao', align: 'right' }, { key: 'returned', label: 'Đã về', align: 'right' }, { key: 'outstanding', label: 'Còn trên xe', align: 'right' }]}
    rows={reconciliation.lines.map((line) => ({ id: `${line.assignmentId}-${line.sku}-${line.lotCode || ''}`, cells: { stop: line.stopSequence, order: line.deliveryOrderNumber || '—', customer: `${line.customerCode || '—'} — ${line.customerName || '—'}`, item: <><strong>{line.itemName}</strong><br />{line.sku}{line.lotCode ? ` · Lô ${line.lotCode}` : ''}</>, result: line.attemptResult ? RESULT_LABELS[line.attemptResult] : 'Chưa có kết quả', issued: `${formatExactDecimal(line.issuedBaseQuantity)} ${line.unitCode}`, delivered: formatExactDecimal(line.deliveredBaseQuantity), returned: formatExactDecimal(line.returnedBaseQuantity), outstanding: formatExactDecimal(line.outstandingBaseQuantity) } }))}
    note={reconciliation.canClose ? 'Đã đối chiếu đủ điều kiện đóng chuyến.' : 'Còn hàng/chứng từ cần đối chiếu trước khi đóng chuyến.'}
    signatures={['Điều phối', 'Thủ kho', 'Tài xế']} testId="trip-reconciliation-print-sheet" />;
}
